const IndianStates = ["Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry"]



const Blocks = {

    //jarkhand
    "Bokaro":["Bermo","Chandankiyari","Chandrapura","Chas","Gumia","Jaridih","Kasmar","Nawadih","Peterwar"],
    "Chatra":["Gidhaur","Itkhori","Kanha Chatti","Kunda","Lawalaung","Mayur Hand","Pathalgora","Pratappur","Shaligram Ram Narayanpur","Simaria","Tandwa"],
    "Deoghar":["Deoghar","Devipur","Karon","Madhupur","Margo Munda","Mohanpur","Palojori","Sarath","Sarwan","Sona Rai Tharhi"],
    "Dhanbad":["Baghmara Cum Katras","Baliapur","Dhanbad Cum Kenduadih Cum Jagata","Gobindpur","Jharia Cum Jorapokhar Cum Sindri","Nirsa Cum Chirkunda","Purbi Tundi","Topchanchi","Tundi"],
    "Dumka":["Dumka","Gopikandar","Jama","Jarmundi","Kathikund","Masalia","Ramgarh","Ranishwar","Saraiyahat","Shikaripara"],
    "Garhwa":["Bardiha","Bhandaria","Bhawnathpur","Bishunpura","Chinia","Danda","Dandai","Dhurki","Garhwa","Kandi","Ketar","Kharaundhi","Majhiaon","Meral","Nagaruntari","Ramkanda","Ramna","Ranka","Sagma"],
    "Giridih":["Bagodar","Bengabad","Birni","Deori","Dhanwar","Dumri","Gande","Gawan","Giridih","Jamua","Pirtanr","Sariya","Tisri"],
    "Godda":["Bashant Rai","Boarijor","Godda","Mahagama","Meherma","Pathargama","Poreyahat","Sundarpahari","Thakurgangti"],
    "Gumla":["Albert Ekka","Basia","Bishunpur","Chainpur","Dumri","Ghaghra","Gumla","Kamdara","Palkot","Raidih","Sisai","Verno"],
    "Hazaribagh":["Barhi","Barkagaon","Barkatha","Bishungarh","Chalkusa","Chauparan","Churchu","Dadi","Daru","Hazaribag","Ichak","Katamdag","Katkamsandi","Keredari","Padma","Tati Jhariya"],
    "Jamtara":["Fatehpur","Jamtara","Karma Tanr Vidyasagar","Kundhit","Nala","Narayanpur"],
    "Khunti":["Erki","Karra","Khunti","Murhu","Rania","Torpa"],
    "Kodarma":["Chandwara","Domchanch","Jainagar","Kodarma","Markacho","Satgawan"],
    "Latehar":["Balumath","Bariyatu","Barwadih","Chandwa","Garu","Herhanj","Latehar","Mahuadanr","Manika"],
    "Lohardaga":["Bhandra","Kairo","Kisko","Kuru","Lohardaga","Peshrar","Senha"],
    "Pakur":["Amrapara","Hiranpur","Litipara","Maheshpur","Pakaur","Pakuria"],
    "Palamu":["Bishrampur","Chainpur","Chhatarpur","Haidernagar","Hariharganj","Hussainabad","Manatu","Medininagar","Mohammad Ganj","Nawa Bazar","Nawadiha Bazar Nawadiha","Nilambar Pitambarpur","Padwa","Pandu","Panki","Patan","Pipra","Satbarwa","Tarhasi","Untari Road"],
    "Pashchimi Singhbhum":["Anandpur","Bandgaon","Chaibasa","Chakradharpur","Goilkera","Gudri","Hat Gamharia","Jagannathpur","Jhinkpani","Khuntpani","Kumardungi","Majhgaon","Manjhari","Manoharpur","Noamundi","Sonua","Tantnagar","Tonto"],
    "Purbi Singhbhum":["Baharagora","Boram","Chakulia","Dhalbhumgarh","Dumaria","Ghatshila","Golmuri Cum Jugsalai","Gurbandha","Musabani","Patamda","Potka"],
    "Ramgarh":["Chitarpur","Dulmi","Gola","Mandu","Patratu","Ramgarh"],
    "Ranchi":["Angara","Bero","Bundu","Burmu","Chanho","Itki","Kanke","Khelari","Lapung","Mandar","Nagri","Namkum","Ormanjhi","Rahe","Ratu","Silli","Sonahatu","Tamar I"],
    "Sahibganj":["Barhait","Barharwa","Borio","Mandro","Pathna","Rajmahal","Sahibganj","Taljhari","Udhwa"],
    "Saraikela Kharsawan":["Adityapur","Chandil","Gobindpur","Ichagarh","Kharsawan","Kuchai","Kukru","Nimdih","Saraikela"],
    "Simdega":["Bano","Bansjor","Bolba","Jaldega","Kersai","Kolebira","Kurdeg","Pakar Tanr","Simdega","Thethaitangar"],


    //chattisgarh
    "Balod": ["Balod", "Dondi", "Nedgaon"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Sarsiwa"],
    "Balrampur": ["Balrampur", "Rajnandgaon", "Tulsipur"],
    "Bastar": ["Bastar", "Jagdalpur", "Kondagaon"],
    "Bemetara": ["Bemetara", "Nandghat", "Sakri"],
    "Bijapur": ["Bijapur", "Bhairamgarh", "Kutru"],
    "Bilaspur": ["Bilaspur", "Kota", "Takhatpur"],
    "Dantewada": ["Dantewada", "Bhairsong", "Geedam"],
    "Dhamtari": ["Dhamtari", "Nagri", "Kurud"],
    "Durg": ["Durg", "Bhilai", "Patan"],
    "Gariaband": ["Gariaband", "Mungeli", "Rajnandgaon"],
    "Janjgir Champa": ["Janjgir", "Champa", "Pali"],
    "Jashpur": ["Jashpur", "Kunkuri", "Bagicha"],
    "Kabirdham": ["Kabirdham", "Bodla", "Pandaria"],
    "Kanker": ["Kanker", "Charama", "Durgukondal"],
    "Kondagaon": ["Kondagaon", "Narayangarh", "Tokapal"],
    "Korba": ["Korba", "Khasgaon", "Katghora"],
    "Koriya": ["Koriya", "Baikunthpur", "Chirmiri"],
    "Mahasamund": ["Mahasamund", "Saraipali", "Pithora"],
    "Mungeli": ["Mungeli", "Bilaspur", "Lormi"],
    "Narayanpur": ["Narayanpur", "Orchha", "Tadok"],
    "Raigarh": ["Raigarh", "Gharghoda", "Kharsia"],
    "Raipur": ["Raipur", "Dhamtari", "Tilda"],
    "Rajnandgaon": ["Rajnandgaon", "Dongargarh", "Kanker"],
    "Sukma": ["Sukma", "Bhairamgarh", "Chhindgarh"],
    "Surajpur": ["Surajpur", "Pratappur", "Sarguja"],
    "Surguja": ["Surguja", "Ambikapur", "Mainpat"],


    // Utter Perdash
    "Agra":["Agra","Bah","Etmadpur","Fatehabad","Kheragarh","Kiraoli"],
    "Aligarh":["Atrauli","Gabhana","Iglas","Khair","Koil"],
    "Allahabad":["Allahabad","Bara","Handia","Karchhana","Koraon","Meja","Phulpur","Soraon"],
    "Ambedkar Nagar":["Akbarpur","Allapur","Bhiti","Jalalpur","Tanda"],
    "Auraiya":["Auraiya","Bidhuna"],
    "Azamgarh":["Azamgarh","Burhanpur","Lalganj","Mehnagar","Nizamabad","Phulpur","Sagri"],
    "Baghpat":["Baghpat","Baraut","Khekada"],
    "Bahraich":["Bahraich","Kaiserganj","Mahasi","Nanpara"],
    "Ballia":["Bairia","Ballia","Bansdih","Belthara Road","Rasra","Sikanderpur"],
    "Balrampur":["Balrampur","Tulsipur","Utraula"],
    "Banda":["Atarra","Baberu","Banda","Naraini"],
    "Bara Banki":["Fatehpur","Haidergarh","Nawabganj","Ramnagar","Ramsanehighat","Sirauli Gauspur"],
    "Bareilly":["Aonla","Baheri","Bareilly","Faridpur","Meerganj","Nawabganj"],
    "Basti":["Basti","Bhanpur","Harraiya","Rudhauli"],
    "Bijnor":["Bijnor","Chandpur","Dhampur","Nagina","Najibabad"],
    "Budaun":["Bilsi","Bisauli","Budaun","Dataganj","Gunnaur","Sahaswan"],
    "Bulandshahr":["Anupshahr","Bulandshahr","Debai","Khurja","Shikarpur","Siana","Sikandrabad"],
    "Chandauli":["Chakia","Chandauli","Sakaldiha"],
    "Chitrakoot":["Karwi","Mau"],
    "Deoria":["Barhaj","Bhatpar Rani","Deoria","Rudrapur","Salempur"],
    "Etah":["Aliganj","Etah","Jalesar"],
    "Etawah":["Bharthana","Chakarnagar","Etawah","Jaswantnagar","Saifai"],
    "Faizabad":["Bikapur","Faizabad","Milkipur","Rudauli","Sohawal"],
    "Farrukhabad":["Amritpur","Farrukhabad","Kaimganj"],
    "Fatehpur":["Bindki","Fatehpur","Khaga"],
    "Firozabad":["Firozabad","Jasrana","Shikohabad","Tundla"],
    "Gautam Buddha Nagar":["Dadri","Gautam Buddha Nagar","Jewar"],
    "Ghaziabad":["Garhmukteshwar","Ghaziabad","Hapur","Modinagar"],
    "Ghazipur":["Ghazipur","Jakhania","Mohammadabad","Saidpur","Zamania"],
    "Gonda":["Colonelganj","Gonda","Mankapur","Tarabganj"],
    "Gorakhpur":["Bansgaon","Campierganj","Chauri Chaura","Gola","Gorakhpur","Khajni","Sahjanwa"],
    "Hamirpur":["Hamirpur","Maudaha","Rath","Sarila"],
    "Hardoi":["Bilgram","Hardoi","Sandila","Sawayajpur","Shahabad"],
    "Jalaun":["Jalaun","Kalpi","Konch","Madhogarh","Orai"],
    "Jaunpur":["Badlapur","Jaunpur","Kerakat","Machhlishahr","Mariahu","Shahganj"],
    "Jhansi":["Garautha","Jhansi","Mauranipur","Moth","Tahrauli"],
    "Jyotiba Phule Nagar":["Amroha","Dhanaura","Hasanpur"],
    "Kannauj":["Chhibramau","Kannauj","Tirwa"],
    "Kanpur Dehat":["Akbarpur","Bhognipur","Derapur","Rasulabad","Sikandra"],
    "Kanpur Nagar":["Bilhaur","Ghatampur","Kanpur"],
    "Kanshiram Nagar":["Kasganj","Patiyali","Sahawar"],
    "Kaushambi":["Chail","Manjhanpur","Sirathu"],
    "Kheri":["Dhaurahara","Gola Gokaran Nath","Lakhimpur","Mohammdi","Nighasan","Palia"],
    "Kushinagar":["Hata","Kasya","Padrauna","Tamkuhi Raj"],
    "Lalitpur":["Lalitpur","Mahroni","Talbehat"],
    "Lucknow":["Bakshi Ka Talab","Lucknow","Malihabad","Mohanlalganj"],
    "Mahamaya Nagar":["Hathras","Sadabad","Sasni","Sikandra Rao"],
    "Mahoba":["Charkhari","Kulpahar","Mahoba"],
    "Mahrajganj":["Maharajganj","Nautanwa","Nichlaul","Pharenda"],
    "Mainpuri":["Bhogaon","Karhal","Mainpuri"],
    "Mathura":["Chhata","Mahavan","Mat","Mathura"],
    "Mau":["Ghosi","Madhuban","Maunath Bhanjan","Muhammadabad Gohna"],
    "Meerut":["Mawana","Meerut","Sardhana"],
    "Mirzapur":["Chunar","Lalganj","Marihan","Mirzapur"],
    "Moradabad":["Bilari","Chandausi","Kanth","Moradabad","Sambhal","Thakurdwara"],
    "Muzaffarnagar":["Budhana","Jansath","Kairana","Khatauli","Muzaffarnagar","Shamli"],
    "Pilibhit":["Bisalpur","Pilibhit","Puranpur"],
    "Pratapgarh":["Kunda","Lalganj","Patti","Pratapgarh","Raniganj"],
    "Rae Bareli":["Dalmau","Lalganj","Maharajganj","Rae Bareli","Salon","Tiloi","Unchahar"],
    "Rampur":["Bilaspur","Milak","Rampur","Shahabad","Suar","Tanda"],
    "Saharanpur":["Behat","Deoband","Nakur","Rampur Maniharan","Saharanpur"],
    "Sant Kabir Nagar":["Ghanghata","Khalilabad","Mehdawal"],
    "Sant Ravidas Nagar":["Aurai","Bhadohi","Gyanpur"],
    "Shahjahanpur":["Jalalabad","Powayan","Shahjahanpur","Tilhar"],
    "Shrawasti":["Bhinga","Ikauna"],
    "Siddharthnagar":["Bansi","Domariyaganj","Itwa","Naugarh","Shohratgarh"],
    "Sitapur":["Biswan","Laharpur","Mahmudabad","Misrikh","Sidhauli","Sitapur"],
    "Sonbhadra":["Dudhi","Ghorawal","Robertsganj"],
    "Sultanpur":["Amethi","Gauriganj","Jaisinghpur","Kadipur","Lambhua","Musafirkhana","Sultanpur"],
    "Unnao":["Bighapur","Hasanganj","Purwa","Safipur","Unnao"],
    "Varanasi":["Pindra","Varanasi"],



    // Delhi
    "Central Delhi": ["Central Delhi"],
    "East Delhi": ["East Delhi"],
    "New Delhi": ["New Delhi"],
    "North Delhi": ["North Delhi"],
    "North East Delhi": ["North East Delhi"],
    "North West Delhi": ["North West Delhi"],
    "Shahdara": ["Shahdara"],
    "South Delhi": ["South Delhi"],
    "South East Delhi": ["South East Delhi"],
    "South West Delhi": ["South West Delhi"],
    "West Delhi": ["West Delhi"],
    // Goa
    "North Goa": ["Bardez", "Bicholim", "Pernem", "Ponda", "Satari", "Tiswadi"],
    "South Goa": ["Canacona", "Mormugao", "Quepem", "Salcete", "Sanguem"],
    // Gujrat
    "Ahmedabad": ["Ahmedabad City", "Daskroi", "Gandhinagar", "Sanand", "Utran"],
    "Amreli": ["Amreli Town", "Lathi", "Vallabhipur", "Dhari", "Gadhda"],
    "Anand": ["Anand Town", "Borsad", "Kheda", "Petlad", "Vallabh Vidyanagar"],
    "Aravalli": ["Aravalli", "Modasa", "Khedbrahma", "Bhiloda", "Malpur"],
    "Banaskantha": ["Banaskantha", "Deesa", "Palanpur", "Tharad", "Vav"],
    "Bharuch": ["Bharuch City", "Ankleshwar", "Narmada", "Jambusar", "Vaghodia"],
    "Bhavnagar": ["Bhavnagar City", "Gadhada", "Mahuva", "Palitana", "Sihor"],
    "Botad": ["Botad", "Gadhada", "Mahuva", "Sihor", "Vallabhipur"],
    "Chhota Udaipur": ["Chhota Udaipur", "Pavi Jetpur", "Ratangarh", "Vaghodia", "Jambughoda"],
    "Dahod": ["Dahod City", "Dhanpur", "Fatepura", "Lunawada", "Rajpipla"],
    "Dang": ["Dang", "Ahwa", "Subir", "Sukhi", "Waghai"],
    "Devbhoomi Dwarka": ["Devbhoomi Dwarka", "Dwarka", "Kachchh", "Okhamandal", "Siddhpur"],
    "Gandhinagar": ["Gandhinagar City", "Kalol", "Mansa", "Pethapur", "Sector 21"],
    "Gir Somnath": ["Gir Somnath", "Veraval", "Gir", "Sasan", "Talala"],
    "Jamnagar": ["Jamnagar City", "Dwarka", "Kalavad", "Jodia", "Rajkot"],
    "Junagadh": ["Junagadh City", "Gir Somnath", "Malia", "Upleta", "Veraval"],
    "Kheda": ["Kheda", "Nadiad", "Matar", "Kapadvanj", "Mehmedabad"],
    "Kutch": ["Kutch", "Bhuj", "Mandvi", "Anjar", "Mundra"],
    "Mahisagar": ["Mahisagar", "Lunawada", "Modasa", "Khedbrahma", "Santrampur"],
    "Mehsana": ["Mehsana City", "Visnagar", "Kadi", "Unjha", "Patan"],
    "Morbi": ["Morbi", "Wankaner", "Jodiya", "Nikol", "Tankara"],
    "Narmada": ["Narmada", "Rajpipla", "Dediapada", "Sagbara", "Sukhi"],
    "Navsari": ["Navsari", "Vapi", "Gandevi", "Valsad", "Dang"],
    "Panchmahal": ["Panchmahal", "Godhra", "Halol", "Khalwa", "Jambughoda"],
    "Patan": ["Patan City", "Siddhpur", "Radhanpur", "Unjha", "Vijapur"],
    "Porbandar": ["Porbandar", "Porbandar City", "Ranavav", "Kutiyana", "Madhavpur"],
    "Rajkot": ["Rajkot City", "Wankaner", "Gondal", "Jetpur", "Upleta"],
    "Sabarkantha": ["Sabarkantha", "Himatnagar", "Idar", "Khedbrahma", "Modasa"],
    "Surat": ["Surat City", "Gopi", "Mandvi", "Kamrej", "Palsana"],
    "Surendranagar": ["Surendranagar", "Wadhwan", "Sangola", "Chotila", "Dhrangadhra"],
    "Tapi": ["Tapi", "Vyara", "Songadh", "Umarpada", "Mandvi"],
    "Vadodara": ["Vadodara City", "Karjan", "Sardar Patel", "Savli", "Vadsar"],
    "Valsad": ["Valsad", "Vapi", "Pardi", "Dangs", "Kaprada"],
    // Haryana
    "Ambala": ["Ambala City", "Ambala Sadar", "Barara", "Naraingarh", "Shahbad"],
    "Bhiwani": ["Bhiwani Town", "Bhiwani Sadar", "Dadri", "Loharu", "Siwani"],
    "Charkhi Dadri": ["Charkhi Dadri", "Badhra", "Bhiwani", "Jhojhu Kalan", "Dabwali"],
    "Faridabad": ["Faridabad City", "Ballabgarh", "Tigaon", "Palwal", "Hathin"],
    "Fatehabad": ["Fatehabad Town", "Ratia", "Tohana", "Fatehabad", "Jhunir"],
    "Gurugram": ["Gurugram City", "Manesar", "Pataudi", "Sohna", "Nuh"],
    "Hisar": ["Hisar City", "Hansi", "Barwala", "Narnaul", "Uklana"],
    "Jhajjar": ["Jhajjar Town", "Bahadurgarh", "Berhampur", "Matenhail", "Bhiwani"],
    "Jind": ["Jind City", "Safidon", "Uchana", "Julana", "Narwana"],
    "Kaithal": ["Kaithal Town", "Pundri", "Guhla", "Kaithal", "Kalayat"],
    "Karnal": ["Karnal City", "Assandh", "Nilokheri", "Indri", "Karnal"],
    "Kurukshetra": ["Kurukshetra City", "Pehowa", "Shahbad", "Thanesar", "Kadwa"],
    "Mahendragarh": ["Mahendragarh Town", "Narnaul", "Ateli", "Kanina", "Madhogarh"],
    "Mewat": ["Nuh", "Firozpur Jhirka", "Pehowa", "Nagina", "Mewat"],
    "Palwal": ["Palwal City", "Hodal", "Tauru", "Palwal", "Pehowa"],
    "Panchkula": ["Panchkula City", "Pinjore", "Kalka", "Barwala", "Raipur"],
    "Panipat": ["Panipat City", "Samalkha", "Kandau", "Gohana", "Panipat"],
    "Rewari": ["Rewari City", "Bawal", "Jatusana", "Kosli", "Jhajjar"],
    "Rohtak": ["Rohtak City", "Maham", "Sampla", "Kalanaur", "Rohtak"],
    "Sirsa": ["Sirsa City", "Rania", "Dabwali", "Ellenabad", "Sirsa"],
    "Sonipat": ["Sonipat City", "Ganaur", "Kharkhoda", "Kundli", "Sonipat"],
    "Yamunanagar": ["Yamunanagar City", "Jagadhri", "Radaur", "Bilaspur", "Yamunanagar"],
    // Himachal Pradesh
    "Bilaspur": ["Bilaspur Town", "Ghumarwin", "Jhandutta", "Kangnuwal", "Sadar"],
    "Chamba": ["Chamba Town", "Bharmaur", "Bhattiyat", "Churah", "Pangi"],
    "Hamirpur": ["Hamirpur Town", "Bani", "Nadaun", "Sujanpur", "Chaupal"],
    "Kangra": ["Dharamshala", "Kangra Town", "Palampur", "Nagrota Bagwan", "Jwalamukhi"],
    "Kinnaur": ["Reckong Peo", "Kinnaur Town", "Kalpa", "Powari", "Nichar"],
    "Kullu": ["Kullu Town", "Manali", "Ani", "Banjar", "Naggar"],
    "Lahaul Spiti": ["Keylong", "Spiti", "Kaza", "Lahaul", "Udaipur"],
    "Mandi": ["Mandi Town", "Sadar", "Sundernagar", "Padhar", "Karsog"],
    "Shimla": ["Shimla Town", "Theog", "Chopal", "Narkand", "Rampur"],
    "Sirmaur": ["Nahan", "Paonta Sahib", "Rajgarh", "Sadar", "Shillai"],
    "Solan": ["Solan Town", "Kasauli", "Nalagarh", "Arki", "Shimla Rural"],
    "Una": ["Una Town", "Amb", "Bangana", "Haroli", "Ghanauli"],

    // J& K
    "Anantnag": ["Anantnag", "Bijbehara", "Kokernag", "Pahalgam", "Srigufwara"],
    "Bandipora": ["Bandipora", "Gurez", "Sumbal", "Hajin", "Arin"],
    "Baramulla": ["Baramulla", "Sopore", "Kupwara", "Uri", "Pattan"],
    "Budgam": ["Budgam", "Chadoora", "Magam", "Beerwah", "Khansahib"],
    "Doda": ["Doda", "Bhaderwah", "Kishtwar", "Assar", "Gandoh"],
    "Ganderbal": ["Ganderbal", "Kangan", "Wangath", "Lar", "Ganderbal Town"],
    "Jammu": ["Jammu", "Jammu City", "Akhnoor", "R.S. Pura", "Bishnah"],
    "Kargil": ["Kargil", "Drass", "Zanskar", "Nubra", "Shargole"],
    "Kathua": ["Kathua", "Kathua City", "Billawar", "Hiranagar", "Basohli"],
    "Kishtwar": ["Kishtwar", "Kishtwar Town", "Padder", "Nagsini", "Chhatru"],
    "Kulgam": ["Kulgam", "Kulgam Town", "Qaimoh", "D.H. Pora", "Yaripora"],
    "Kupwara": ["Kupwara", "Kupwara Town", "Handwara", "Langate", "Kalaroos"],
    "Leh": ["Leh", "Leh Town", "Nubra", "Zanskar", "Sham"],
    "Poonch": ["Poonch", "Poonch Town", "Surankote", "Mendhar", "Sankoo"],
    "Pulwama": ["Pulwama", "Pulwama Town", "Tral", "Awantipora", "Kakapora"],
    "Rajouri": ["Rajouri", "Rajouri Town", "Nowshera", "Sunderbani", "Kalakote"],
    "Ramban": ["Ramban", "Ramban Town", "Banihal", "Gool", "Batote"],
    "Reasi": ["Reasi", "Reasi Town", "Mahore", "Katra", "Arnas"],
    "Samba": ["Samba", "Samba Town", "Vijaypur", "Purmandal", "Ramgarh"],
    "Shopian": ["Shopian", "Shopian Town", "Herman", "Keller", "Wachi"],
    "Srinagar": ["Srinagar", "Srinagar City", "Downtown Srinagar", "North Srinagar", "South Srinagar"],
    "Udhampur": ["Udhampur", "Udhampur Town", "Rehambal", "Chenani", "Majalta"],
    // Karnataka
    "Bagalkot": ["Bagalkot", "Badami", "Bagalkot Town", "Kudala Sangama", "Hunagund"],
    "Bangalore Rural": ["Bangalore Rural", "Doddaballapura", "Nelamangala", "Devanahalli", "Vijayanagara"],
    "Bangalore Urban": ["Bangalore Urban", "Bangalore", "Bangalore South", "Bangalore East", "Bangalore North"],
    "Belgaum": ["Belgaum", "Belgaum City", "Chikodi", "Gokak", "Hubli"],
    "Bellary": ["Bellary", "Bellary City", "Hospet", "Sandur", "Koppal"],
    "Bidar": ["Bidar", "Bidar City", "Basavakalyan", "Humnabad", "Bhalki"],
    "Vijayapura": ["Vijayapura", "Vijayapura City", "Bagalkot", "Basavana Bagewadi", "Indi"],
    "Chamarajanagar": ["Chamarajanagar", "Chamarajanagar City", "Kollegal", "Yelandur", "Nanjangud"],
    "Chikkaballapur": ["Chikkaballapur", "Chikkaballapur City", "Bagepalli", "Gauribidanur", "Shidlaghatta"],
    "Chikkamagaluru": ["Chikkamagaluru", "Chikkamagaluru City", "Mudigere", "Kadur", "Koppa"],
    "Chitradurga": ["Chitradurga", "Chitradurga City", "Hosadurga", "Hiriyur", "Holalkere"],
    "Dakshina Kannada": ["Dakshina Kannada", "Mangalore", "Udupi", "Karkala", "Moodabidri"],
    "Davanagere": ["Davanagere", "Davanagere City", "Harihar", "Honnali", "Jagalur"],
    "Dharwad": ["Dharwad", "Dharwad City", "Hubli", "Kalghatgi", "Navalgund"],
    "Gadag": ["Gadag", "Gadag City", "Bagalkot", "Koppal", "Ron"],
    "Gulbarga": ["Gulbarga", "Gulbarga City", "Chincholi", "Kalaburagi", "Yadgir"],
    "Hassan": ["Hassan", "Hassan City", "Channarayapatna", "Arsikere", "Belur"],
    "Haveri": ["Haveri", "Haveri City", "Ranebennur", "Shiggavi", "Savanur"],
    "Kodagu": ["Kodagu", "Madikeri", "Virajpet", "Somwarpet", "Kodagu Town"],
    "Kolar": ["Kolar", "Kolar City", "Malur", "Mulbagal", "Bangarapet"],
    "Koppal": ["Koppal", "Koppal City", "Kushtagi", "Gangavathi", "Yelburga"],
    "Mandya": ["Mandya", "Mandya City", "Srirangapatna", "Melukote", "Panda"],
    "Mysore": ["Mysore", "Mysore City", "Nanjangud", "Hunsur", "Krishnarajanagara"],
    "Raichur": ["Raichur", "Raichur City", "Lingasugur", "Manvi", "Sindhanur"],
    "Ramanagara": ["Ramanagara", "Ramanagara City", "Channapatna", "Kanakapura", "Magadi"],
    "Shimoga": ["Shimoga", "Shimoga City", "Sagar", "Shikaripur", "Tirthahalli"],
    "Tumkur": ["Tumkur", "Tumkur City", "Tiptur", "Pavagada", "Koratagere"],
    "Udupi": ["Udupi", "Udupi City", "Kundapura", "Karkala", "Malpe"],
    "Uttara Kannada": ["Uttara Kannada", "Karwar", "Sirsi", "Honavar", "Dandeli"],
    "Yadgir": ["Yadgir", "Yadgir City", "Shahapur", "Gulbarga", "Raichur"],
    // Kerala
    "Alappuzha": ["Alappuzha", "Cherthala", "Chengannur", "Mavelikkara", "Punnamada"],
    "Ernakulam": ["Ernakulam", "Kochi", "Kothamangalam", "Muvattupuzha", "Tripunithura"],
    "Idukki": ["Idukki", "Munnar", "Kattappana", "Peermade", "Devikulam"],
    "Kannur": ["Kannur", "Thalassery", "Payyannur", "Sreekandapuram", "Taliparamba"],
    "Kasaragod": ["Kasaragod", "Cheruvathur", "Kanhangad", "Nileshwar", "Bekal"],
    "Kollam": ["Kollam", "Kottarakkara", "Paravur", "Punalur", "Karunagappally"],
    "Kottayam": ["Kottayam", "Changanassery", "Pala", "Meenachy", "Vaikom"],
    "Kozhikode": ["Kozhikode", "Calicut", "Quilandy", "Kunnamangalam", "Perambra"],
    "Malappuram": ["Malappuram", "Perinthalmanna", "Kondotty", "Nilambur", "Tirur"],
    "Palakkad": ["Palakkad", "Ottapalam", "Mannarkkad", "Pattambi", "Cherpulassery"],
    "Pathanamthitta": ["Pathanamthitta", "Elanthoor", "Kozhencherry", "Thiruvalla", "Ranni"],
    "Thiruvananthapuram": ["Thiruvananthapuram", "Kovalam", "Nedumangad", "Vattiyoorkavu", "Parassala"],
    "Thrissur": ["Thrissur", "Irinjalakuda", "Chalakudy", "Kodungallur", "Kunnamkulam"],
    "Wayanad": ["Wayanad", "Kalpetta", "Sultan Bathery", "Mananthavady", "Vythiri"],
    
    // Lakshadeep
    "Lakshadweep": ["Agatti", "Amini", "Andrott", "Bitra", "Chetlat", "Kadmat", "Kalpeni", "Kavaratti", "Kiltan", "Minicoy"],

    // Madhya Pradesh
    "Alirajpur":["Alirajpur","Bhavra","Jobat"],
    "Anuppur":["Anuppur","Jaithari","Kotma","Pushparajgarh"],
    "Ashoknagar":["Ashoknagar","Chanderi","Isagarh","Mungaoli","Shadhora"],
    "Balaghat":["Baihar","Balaghat","Katangi","Khairlanji","Kirnapur","Lalbarra","Lanji","Paraswada","Tirodi","Waraseoni"],
    "Barwani":["Anjad","Barwani","Niwali","Pansemal","Pati","Rajpur","Sendhwa","Thikri","Varla"],
    "Betul":["Amla","Athner","Betul","Bhainsdehi","Chicholi","Ghoda Dongri","Multai","Shahpur"],
    "Bhind":["Ater","Bhind","Gohad","Gormi","Lahar","Mehgaon","Mihona","Ron"],
    "Bhopal":["Berasia","Huzur"],
    "Burhanpur":["Burhanpur","Khaknar","Nepanagar"],
    "Chhatarpur":["Bada Malhera","Bijawar","Buxwaha","Chandla","Chhatarpur","Gaurihar","Ghuwara","Laundi","Maharajpur","Nowgong","Rajnagar"],
    "Chhindwara":["Amarwara","Bichhua","Chaurai","Chhindwara","Harrai","Jamai","Mohkhed","Pandhurna","Parasia","Sausar","Tamia","Umreth"],
    "Damoh":["Batiyagarh","Damoh","Hatta","Jabera","Patera","Patharia","Tendukheda"],
    "Datia":["Bhander","Datia","Indergarh","Seondha"],
    "Dewas":["Bagli","Dewas","Hatpiplya","Kannod","Khategaon","Satwas","Sonkatch","Tonk Khurd"],
    "Dhar":["Badnawar","Dahi","Dhar","Dharampuri","Gandhwani","Kukshi","Manawar","Sardarpur"],
    "Dindori":["Dindori","Shahpura"],
    "Guna":["Aron","Bamori","Chachaura","Guna","Kumbhraj","Maksoodangarh","Raghogarh"],
    "Gwalior":["Bhitarwar","Chinour","Dabra","Gwalior"],
    "Harda":["Handiya","Harda","Khirkiya","Rehatgaon","Sirali","Timarni"],
    "Hoshangabad":["Babai","Bankhedi","Dolariya","Hoshangabad","Itarsi","Pipariya","Seoni Malwa","Sohagpur"],
    "Indore":["Depalpur","Hatod","Indore","Mhow","Sawer"],
    "Jabalpur":["Jabalpur","Kundam","Majholi","Panagar","Patan","Shahpura","Sihora"],
    "Jhabua":["Jhabua","Meghnagar","Petlawad","Ranapur","Thandla"],
    "Katni":["Badwara","Bahoriband","Barhi","Dhimarkheda","Murwara","Rithi","Vijayraghavgarh"],
    "Khandwa":["Harsud","Khalwa","Khandwa","Pandhana","Punasa"],
    "Khargone":["Barwaha","Bhagwanpura","Bhikangaon","Gogaon","Jhiranya","Kasrawad","Khargone","Maheshwar","Segaon"],
    "Mandla":["Bichhiya","Ghughari","Mandla","Nainpur","Narayanganj","Niwas"],
    "Mandsaur":["Bhanpura","Daloda","Garoth","Malhargarh","Mandsaur","Shamgarh","Sitamau","Suwasara"],
    "Morena":["Ambah","Joura","Kailaras","Morena","Porsa","Sabalgarh"],
    "Narsimhapur":["Gadarwara","Gotegaon","Kareli","Narsimhapur","Tendukheda"],
    "Neemuch":["Jawad","Jiran","Manasa","Neemuch","Singoli"],
    "Panna":["Ajaigarh","Amanganj","Devendranagar","Gunnor","Panna","Pawai","Raipura","Shahnagar"],
    "Raisen":["Badi","Baraily","Begamganj","Gairatganj","Goharganj","Raisen","Silwani","Udaipura"],
    "Rajgarh":["Biaora","Jirapur","Khilchipur","Narsinghgarh","Pachore","Rajgarh","Sarangpur"],
    "Ratlam":["Alot","Bajna","Jaora","Piploda","Ratlam","Rawti","Sailana","Tal"],
    "Rewa":["Gurh","Hanumana","Huzur","Jawa","Mangawan","Mauganj","Naigarhi","Raipur Karchuliyan","Semaria","Sirmour","Teonthar"],
    "Sagar":["Banda","Bina","Deori","Garhakota","Kesli","Khurai","Malthon","Rahatgarh","Rehli","Sagar","Shahgarh"],
    "Satna":["Amarpatan","Birsinghpur","Kotar","Maihar","Majhgawan","Nagod","Raghurajnagar","Ramnagar","Rampur Baghelan","Unchahara"],
    "Sehore":["Ashta","Budni","Ichhawar","Jawar","Nasrullaganj","Rehti","Sehore","Shyampur"],
    "Seoni":["Barghat","Chhapara","Dhanora","Ghansaur","Keolari","Kurai","Lakhnadon","Seoni"],
    "Shahdol":["Beohari","Jaisinghnagar","Jaitpur","Sohagpur"],
    "Shajapur":["Agar","Badod","Gulana","Kalapipal","Moman Badodiya","Nalkheda","Shajapur","Shujalpur","Susner"],
    "Shajapur":["Agar","Badod","Gulana","Kalapipal","Moman Badodiya","Nalkheda","Shajapur","Shujalpur","Susner"],
    "Sheopur":["Badoda","Beerpur","Karahal","Sheopur","Vijaypur"],
    "Shivpuri":["Badarwas","Karera","Khaniyadhana","Kolaras","Narwar","Pichhore","Pohri","Shivpuri"],
    "Sidhi":["Churhat","Gopadbanas","Kusmi","Majhauli","Rampur Naikin","Sihawal"],
    "Singrauli":["Chitrangi","Deosar","Singrauli"],
    "Singrauli":["Chitrangi","Deosar","Singrauli"],
    "Tikamgarh":["Baldeogarh","Jatara","Khargapur","Mohangarh","Niwari","Orchha","Palera","Prithvipur","Tikamgarh"],
    "Ujjain":["Badnagar","Ghatiya","Khacharod","Mahidpur","Nagda","Tarana","Ujjain"],
    "Umaria":["Bandhogarh","Chandia","Manpur","Nowrozabad","Pali"],
    "Umaria":["Bandhogarh","Chandia","Manpur","Nowrozabad","Pali"],



    // Maharastra
    "Ahmednagar": ["Ahmednagar", "Akole", "Ahmednagar Rural", "Pathardi"],
    "Akola": ["Akola", "Akot", "Murtijapur", "Patur"],
    "Amravati": ["Amravati", "Achalpur", "Morshi", "Chandur"],
    "Aurangabad": ["Aurangabad", "Aurangabad City", "Chikhalthana", "Paithan"],
    "Beed": ["Beed", "Ambajogai", "Patoda", "Wadwani"],
    "Bhandara": ["Bhandara", "Tumsar", "Lakhandur", "Sakoli"],
    "Buldhana": ["Buldhana", "Khamgaon", "Malkapur", "Shegaon"],
    "Chandrapur": ["Chandrapur", "Ballarpur", "Bramhapuri", "Warora"],
    "Dhule": ["Dhule", "Nandurbar", "Shahada", "Sakri"],
    "Gadchiroli": ["Gadchiroli", "Armori", "Dhanora", "Etapalli"],
    "Gondia": ["Gondia", "Tirora", "Deori", "Amgaon"],
    "Hingoli": ["Hingoli", "Aundha", "Khandala", " Hingoli"],
    "Jalgaon": ["Jalgaon", "Bhusawal", "Jalgaon Rural", "Raver"],
    "Jalna": ["Jalna", "Ambad", "Bhokardan", "Ghansawangi"],
    "Kolhapur": ["Kolhapur", "Kagal", "Radhanagari", "Shahuwadi"],
    "Latur": ["Latur", "Ausa", "Jalkot", "Udgir"],
    "Mumbai City": ["Mumbai City", "Colaba", "Fort", "Marine Drive"],
    "Mumbai Suburban": ["Mumbai Suburban", "Andheri", "Bandra", "Malad"],
    "Nagpur": ["Nagpur", "Nagpur City", "Kamptee", "Umred"],
    "Nanded": ["Nanded", "Bhokar", "Ardhapur", "Hingoli"],
    "Nandurbar": ["Nandurbar", "Akkalkuwa", "Taloda", "Shahada"],
    "Nashik": ["Nashik", "Nashik City", "Igatpuri", "Sinnar"],
    "Osmanabad": ["Osmanabad", "Tuljapur", "Kallam", "Omerga"],
    "Palghar": ["Palghar", "Vasai", "Nalasopara", "Boisar"],
    "Parbhani": ["Parbhani", "Jintur", "Pathri", "Purna"],
    "Pune": ["Pune", "Pimpri-Chinchwad", "Lonavala", "Khed"],
    "Raigad": ["Raigad", "Alibag", "Pen", "Murud"],
    "Ratnagiri": ["Ratnagiri", "Chiplun", "Khed", "Dapoli"],
    "Sangli": ["Sangli", "Miraj", "Kavathemahankal", "Atpadi"],
    "Satara": ["Satara", "Karad", "Patan", "Walwa"],
    "Sindhudurg": ["Sindhudurg", "Malvan", "Kankavli", "Sawantwadi"],
    "Solapur": ["Solapur", "Solapur City", "Pandharpur", "Mangalvedhe"],
    "Thane": ["Thane", "Kalyan", "Ulhasnagar", "Bhiwandi"],
    "Wardha": ["Wardha", "Arvi", "Hinganghat", "Seloo"],
    "Washim": ["Washim", "Akola", "Khamgaon", "Mangrulpir"],
    "Yavatmal": ["Yavatmal", "Pusad", "Arni", "Vijayapuri"],
    // Chhattisgarh
    "Balod": ["Balod", "Dondi", "Gunderdehi", "Ladum"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Palari", "Sakri"],
    "Balrampur": ["Balrampur", "Ramanujganj", "Kusmi", "Saryapath"],
    "Bastar": ["Bastar", "Jagdalpur", "Narayanpur", "Kondagaon"],
    "Bemetara": ["Bemetara", "Saja", "Nayapara", "Pali"],
    "Bijapur": ["Bijapur", "Bhopalpatnam", "Kamptee", "Madded"],
    "Bilaspur": ["Bilaspur", "Bilaspur Town", "Kargi", "Kotma"],
    "Dantewada": ["Dantewada", "Bijapur", "Kisdag", "Sukma"],
    "Dhamtari": ["Dhamtari", "Kurud", "Nagri", "Sihawa"],
    "Durg": ["Durg", "Bhilai", "Durg Town", "Patan"],
    "Gariaband": ["Gariaband", "Nawapara", "Rajim", "Tilda"],
    "Janjgir Champa": ["Janjgir", "Champa", "Malkangiri", "Pathalgaon"],
    "Jashpur": ["Jashpur", "Bagicha", "Kunkuri", "Pali"],
    "Kabirdham": ["Kabirdham", "Kawardha", "Pandariya", "Sahaspur"],
    "Kanker": ["Kanker", "Dantewada", "Keshkal", "Naxal"],
    "Kondagaon": ["Kondagaon", "Kondagaon Town", "Narayanpur", "Tadoki"],
    "Korba": ["Korba", "Korba Town", "Jangir", "Kusmunda"],
    "Koriya": ["Koriya", "Baikunthpur", "Janakpur", "Pali"],
    "Mahasamund": ["Mahasamund", "Mahasamund Town", "Saraipali", "Tilda"],
    "Mungeli": ["Mungeli", "Mungeli Town", "Patharia", "Lormi"],
    "Narayanpur": ["Narayanpur", "Narayanpur Town", "Kanker", "Kondagaon"],
    "Raigarh": ["Raigarh", "Raigarh Town", "Kharsia", "Sarangarh"],
    "Raipur": ["Raipur", "Raipur City", "Arang", "Balodabazar"],
    "Rajnandgaon": ["Rajnandgaon", "Rajnandgaon Town", "Dongargarh", "Kawardha"],
    "Sukma": ["Sukma", "Sukma Town", "Dantewada", "Bhopalpatnam"],
    "Surajpur": ["Surajpur", "Surajpur Town", "Korwa", "Sarguja"],
    "Surguja": ["Surguja", "Ambikapur", "Kunkuri", "Udaipur"],
    // Manipur
    "Bishnupur": ["Bishnupur", "Bishnupur Town", "Moirang", "Nambol"],
    "Chandel": ["Chandel", "Chandel Town", "Machi", "Moreh"],
    "Churachandpur": ["Churachandpur", "Churachandpur Town", "Henglep", "Parbung"],
    "Imphal East": ["Imphal East", "Khurai", "Lamlai", "Nongren"],
    "Imphal West": ["Imphal West", "Imphal", "Yaiskul", "Kanglatongbi"],
    "Jiribam": ["Jiribam", "Jiribam Town", "Durgapur", "Kumarghat"],
    "Kakching": ["Kakching", "Kakching Town", "Kakching Khunou", "Yairipok"],
    "Kamjong": ["Kamjong", "Kamjong Town", "Khamenlok", "Saikul"],
    "Kangpokpi": ["Kangpokpi", "Kangpokpi Town", "Kanglatongbi", "T Waichong"],
    "Noney": ["Noney", "Noney Town", "Noney Sub-Division", "Lamboi Khongnang"],
    "Pherzawl": ["Pherzawl", "Pherzawl Town", "Henglep", "Saikot"],
    "Senapati": ["Senapati", "Senapati Town", "Kangpokpi", "Karam"],
    "Tamenglong": ["Tamenglong", "Tamenglong Town", "Nungba", "Tamei"],
    "Tengnoupal": ["Tengnoupal", "Tengnoupal Town", "Mongjam", "Kakching"],
    "Thoubal": ["Thoubal", "Thoubal Town", "Wangjing", "Kakching"],
    "Ukhrul": ["Ukhrul", "Ukhrul Town", "Khangshang", "Litan"],

    // Meghalaya
    "East Garo Hills": ["Williamnagar", "Bopung", "Kherapara", "Songsak"],
    "East Jaintia Hills": ["Jowai", "Khliehriat", "Nongstoin", "Mooirang"],
    "East Khasi Hills": ["Shillong", "Nongpoh", "Mawkynrew", "Pynursla"],
    "North Garo Hills": ["Rongjeng", "Bajengdoba", "Resubelpara", "Dainadubi"],
    "Ri Bhoi": ["Nongpoh", "Jirang", "Rangthong", "Khasi"],
    "South Garo Hills": ["Bajengdoba", "Bagmara", "Dudnai", "Rongara"],
    "South West Garo Hills": ["Ampati", "Rangapara", "Chokpot", "Betasing"],
    "South West Khasi Hills": ["Mawkyrwat", "Nongstoin", "Laitkroh", "Nongtrai"],
    "West Garo Hills": ["Tura", "Selsella", "Phulbari", "Rongram"],
    "West Jaintia Hills": ["Jowai", "Mooirang", "Thadlaskein", "Nongjri"],
    "West Khasi Hills": ["Nongstoin", "Mairang", "Mawkyrwat", "Mawkynrew"],

    // Mizoram
    "Aizawl": ["Aizawl", "Aizawl City", "Saitual", "Hnahthial"],
    "Champhai": ["Champhai", "Champhai Town", "Khawzawl", "Serchhip"],
    "Kolasib": ["Kolasib", "Kolasib Town", "Hnahthial", "Bairabi"],
    "Lawngtlai": ["Lawngtlai", "Lawngtlai Town", "Lunglei", "Saiha"],
    "Lunglei": ["Lunglei", "Lunglei Town", "Tlabung", "Khawzawl"],
    "Mamit": ["Mamit", "Mamit Town", "Kolasib", "Hnahthial"],
    "Saiha": ["Saiha", "Saiha Town", "Lawngtlai", "Serchhip"],
    "Serchhip": ["Serchhip", "Serchhip Town", "Lunglei", "Champhai"],
    // Nagaland
    "Dimapur": ["Dimapur", "Dimapur Town", "Chumoukedima", "Dhansiripar"],
    "Kiphire": ["Kiphire", "Kiphire Town", "Pungro", "Sangtam"],
    "Kohima": ["Kohima", "Kohima Town", "Jotsoma", "Zubza"],
    "Longleng": ["Longleng", "Longleng Town", "Changtongya", "Longleng East"],
    "Mokokchung": ["Mokokchung", "Mokokchung Town", "Changki", "Kohima"],
    "Mon": ["Mon", "Mon Town", "Naginimora", "Mokokchung"],
    "Peren": ["Peren", "Peren Town", "Bokajan", "Peren Rural"],
    "Phek": ["Phek", "Phek Town", "Meluri", "Chozuba"],
    "Tuensang": ["Tuensang", "Tuensang Town", "Changsang", "Longkhim"],
    "Wokha": ["Wokha", "Wokha Town", "Bhandari", "Sanis"],
    "Zunheboto": ["Zunheboto", "Zunheboto Town", "Satoi", "Akuluto"],


    // Odisa
    "Angul": ["Angul", "Athmallik", "Chhendipada", "Pallahara"],
    "Balangir": ["Balangir", "Bhawanipatna", "Deogarh", "Titilagarh"],
    "Balasore": ["Balasore", "Baliapal", "Jaleswar", "Soro"],
    "Bargarh": ["Bargarh", "Barpali", "Bhatli", "Sohela"],
    "Bhadrak": ["Bhadrak", "Bansada", "Dhamnagar", "Tihidi"],
    "Boudh": ["Boudh", "Baudh", "Rairakhol", "Subarnapur"],
    "Cuttack": ["Cuttack", "Cuttack City", "Cuttack Rural", "Baranga"],
    "Debagarh": ["Debagarh", "Deogarh", "Reamal", "Tileibani"],
    "Dhenkanal": ["Dhenkanal", "Dhenkanal Town", "Kankadahada", "Kamakhyanagar"],
    "Gajapati": ["Gajapati", "Ganjam", "Mohana", "R Udayagiri"],
    "Ganjam": ["Ganjam", "Berhampur", "Chatrapur", "Bhanjanagar"],
    "Jagatsinghpur": ["Jagatsinghpur", "Jagatsinghpur Town", "Naugaon", "Tirtol"],
    "Jajpur": ["Jajpur", "Jajpur Town", "Binjharpur", "Dasarathpur"],
    "Jharsuguda": ["Jharsuguda", "Jharsuguda Town", "Laikera", "Kolabira"],
    "Kalahandi": ["Kalahandi", "Bhawanipatna", "Kesinga", "Kantabanji"],
    "Kandhamal": ["Kandhamal", "Phulbani", "Baliguda", "Chhendipada"],
    "Kendrapara": ["Kendrapara", "Kendrapara Town", "Aul", "Rajkanika"],
    "Kendujhar": ["Kendujhar", "Kendujhar Town", "Barbil", "Joda"],
    "Khordha": ["Khordha", "Bhubaneswar", "Jatni", "Khurda"],
    "Koraput": ["Koraput", "Jeypore", "Nabarangpur", "Kotpad"],
    "Malkangiri": ["Malkangiri", "Malkangiri Town", "Kalimela", "Mathili"],
    "Mayurbhanj": ["Mayurbhanj", "Baripada", "Rairangpur", "Kaptipada"],
    "Nabarangpur": ["Nabarangpur", "Nabarangpur Town", "Umerkote", "Bamkuda"],
    "Nayagarh": ["Nayagarh", "Nayagarh Town", "Odagaon", "Daspalla"],
    "Nuapada": ["Nuapada", "Nuapada Town", "Khariar", "Khetrajpur"],
    "Puri": ["Puri", "Puri Town", "Konark", "Satyabadi"],
    "Rayagada": ["Rayagada", "Rayagada Town", "Gunupur", "Padmapur"],
    "Sambalpur": ["Sambalpur", "Sambalpur Town", "Rairakhol", "Bargarh"],
    "Subarnapur": ["Subarnapur", "Subarnapur Town", "Birmaharajpur", "Tarabha"],
    "Sundergarh": ["Sundergarh", "Sundergarh Town", "Rourkela", "Rajgangpur"],



    // Pondicherry

    "Karaikal": ["Karaikal", "Karaikal City", "Karaikal South", "Karaikal North"],
    "Mahe": ["Mahe", "Mahe City"],
    "Puducherry": ["Puducherry", "Puducherry City", "Puducherry Rural", "Auroville"],
    "Yanam": ["Yanam", "Yanam City"],

    //Punjab

    "Amritsar": ["Amritsar", "Ajnala", "Tarn Taran", "Raja Sansi"],
    "Barnala": ["Barnala", "Handiaya", "Sanghera", "Shahpur"],
    "Bathinda": ["Bathinda", "Bathinda Rural", "Mansa", "Rampura"],
    "Faridkot": ["Faridkot", "Jaitu", "Kotkapura", "Moga"],
    "Fatehgarh Sahib": ["Fatehgarh Sahib", "Khamano", "Sirhind", "Mandi Gobindgarh"],
    "Fazilka": ["Fazilka", "Abohar", "Jalalabad", "Fazilka"],
    "Firozpur": ["Firozpur", "Firozpur Cantt", "Zira", "Moga"],
    "Gurdaspur": ["Gurdaspur", "Batala", "Dera Baba Nanak", "Pathankot"],
    "Hoshiarpur": ["Hoshiarpur", "Dasuya", "Mukerian", "Talwara"],
    "Jalandhar": ["Jalandhar", "Jalandhar Cantt", "Phagwara", "Nakodar"],
    "Kapurthala": ["Kapurthala", "Kapurthala Rural", "Sultanpur Lodhi", "Begowal"],
    "Ludhiana": ["Ludhiana", "Ludhiana East", "Ludhiana West", "Mandi Ahmedgarh"],
    "Mansa": ["Mansa", "Budhlada", "Mansa Rural", "Jhumba"],
    "Moga": ["Moga", "Moga Rural", "Bajakhana", "Kot Ise Khan"],
    "Mohali": ["Mohali", "S.A.S. Nagar", "Kharar", "Dera Bassi"],
    "Muktsar": ["Muktsar", "Gidderbaha", "Lambi", "Malout"],
    "Pathankot": ["Pathankot", "Pathankot Cantt", "Dalhousie", "Sujanpur"],
    "Patiala": ["Patiala", "Patiala Rural", "Rajpura", "Samana"],
    "Rupnagar": ["Rupnagar", "Ropar", "Nangal", "Kirpalpur"],
    "Sangrur": ["Sangrur", "Sunam", "Dhuri", "Barnala"],
    "Shaheed Bhagat Singh Nagar": ["Shaheed Bhagat Singh Nagar", "Nawanshahr", "Balachaur", "Garhshankar"],
    "Tarn Taran": ["Tarn Taran", "Tarn Taran Rural", "Khemkaran", "Patti"],


    // Rajasthan


    "Ajmer": ["Ajmer", "Beawar", "Kishangarh", "Nasirabad"],
    "Alwar": ["Alwar", "Bhiwadi", "Kishangarh", "Rajgarh"],
    "Banswara": ["Banswara", "Kushalgarh", "Ghatol", "Sarthebari"],
    "Baran": ["Baran", "Chhabra", "Kishanganj", "Sambhar"],
    "Barmer": ["Barmer", "Balotra", "Jaisalmer", "Raniwara"],
    "Bharatpur": ["Bharatpur", "Bayana", "Deeg", "Kumher"],
    "Bhilwara": ["Bhilwara", "Rajsamand", "Mandalgarh", "Shahpura"],
    "Bikaner": ["Bikaner", "Nokha", "Palanpur", "Karanpur"],
    "Bundi": ["Bundi", "Keshoraipatan", "Indergarh", "Lakheri"],
    "Chittorgarh": ["Chittorgarh", "Nimbahera", "Ratanpur", "Kapasan"],
    "Churu": ["Churu", "Ratangarh", "Sardarshahar", "Taranagar"],
    "Dausa": ["Dausa", "Lalsot", "Raya", "Baswa"],
    "Dholpur": ["Dholpur", "Bari", "Rajakhera", "Sarmathura"],
    "Dungarpur": ["Dungarpur", "Bichhiwara", "Sagwara", "Simalwara"],
    "Ganganagar": ["Ganganagar", "Anupgarh", "Padampur", "Ramsinghpur"],
    "Hanumangarh": ["Hanumangarh", "Rawatsar", "Nohar", "Sangaria"],
    "Jaipur": ["Jaipur", "Jaipur City", "Rajasthan", "Sanganer"],
    "Jaisalmer": ["Jaisalmer", "Sam", "Barmer", "Ramdevra"],
    "Jalore": ["Jalore", "Sanchore", "Raniwara", "Bhinmal"],
    "Jhalawar": ["Jhalawar", "Khanpur", "Pipalda", "Ratangarh"],
    "Jhunjhunu": ["Jhunjhunu", "Chirawa", "Alsisar", "Pilani"],
    "Jodhpur": ["Jodhpur", "Osian", "Phalodi", "Luni"],
    "Karauli": ["Karauli", "Hindaun", "Todabhim", "Sapotra"],
    "Kota": ["Kota", "Bundi", "Keshoraipatan", "Baran"],
    "Nagaur": ["Nagaur", "Merta", "Degana", "Khimsar"],
    "Pali": ["Pali", "Rani", "Sojat", "Marwar Junction"],
    "Pratapgarh": ["Pratapgarh", "Chhoti Sadri", "Arnod", "Parel"],
    "Rajsamand": ["Rajsamand", "Kankroli", "Nathdwara", "Udaipur"],
    "Sawai Madhopur": ["Sawai Madhopur", "Lalsot", "Madhopur", "Chauth Ka Barwara"],
    "Sikar": ["Sikar", "Danta Ramgarh", "Palsana", "Laxmangarh"],
    "Sirohi": ["Sirohi", "Abu Road", "Sheoganj", "Raniwara"],
    "Tonk": ["Tonk", "Deoli", "Malpura", "Niwai"],
    "Udaipur": ["Udaipur", "Gogunda", "Kherwara", "Salumbar"],

    //Sikkim
    "East Sikkim": ["Gangtok", "Rangpo", "Singtam", "Pakyong"],
    "North Sikkim": ["Mangan", "Lachen", "Lachung", "Thangu"],
    "South Sikkim": ["Namchi", "Jorethang", "Melli", "Ravangla"],
    "West Sikkim": ["Gyalshing", "Pelling", "Yuksom", "Dentam"],

    //Tamil Nadu
    "Ariyalur": ["Ariyalur", "Sendurai", "Udayarpalayam", "Vennandur"],
    "Chennai": ["Chennai", "Chennai Central", "Chennai North", "Chennai South"],
    "Coimbatore": ["Coimbatore", "Coimbatore North", "Coimbatore South", "Pollachi"],
    "Cuddalore": ["Cuddalore", "Cuddalore Town", "Nellikuppam", "Panruti"],
    "Dharmapuri": ["Dharmapuri", "Dharmapuri Town", "Harur", "Pennagaram"],
    "Dindigul": ["Dindigul", "Dindigul Town", "Kodaikanal", "Nilakottai"],
    "Erode": ["Erode", "Erode Town", "Bhavani", "Perundurai"],
    "Kanchipuram": ["Kanchipuram", "Kanchipuram Town", "Sriperumbudur", "Pallavaram"],
    "Kanyakumari": ["Kanyakumari", "Nagercoil", "Padmanabhapuram", "Thuckalay"],
    "Karur": ["Karur", "Karur Town", "Aravakurichi", "Kudimianmalai"],
    "Krishnagiri": ["Krishnagiri", "Krishnagiri Town", "Hosur", "Rural"],
    "Madurai": ["Madurai", "Madurai Town", "Peraiyur", "Melur"],
    "Nagapattinam": ["Nagapattinam", "Nagapattinam Town", "Sirkali", "Tharangambadi"],
    "Namakkal": ["Namakkal", "Namakkal Town", "Tiruchengode", "Rasipuram"],
    "Nilgiris": ["Nilgiris", "Udhagamandalam", "Coonoor", "Kotagiri"],
    "Perambalur": ["Perambalur", "Perambalur Town", "Veppur", "Kunnam"],
    "Pudukkottai": ["Pudukkottai", "Pudukkottai Town", "Alangudi", "Thirumayam"],
    "Ramanathapuram": ["Ramanathapuram", "Ramanathapuram Town", "Kadaladi", "Paramakudi"],
    "Salem": ["Salem", "Salem Town", "Mettur", "Omalur"],
    "Sivaganga": ["Sivaganga", "Sivaganga Town", "Karaikudi", "Pudukkottai"],
    "Thanjavur": ["Thanjavur", "Thanjavur Town", "Kumbakonam", "Peravurani"],
    "Theni": ["Theni", "Bodinayakkanur", "Periyakulam", "Uthamapalayam"],



    //Telangana
    "Adilabad": ["Adilabad", "Konta", "Kumram Bheem", "Utnoor"],
    "Bhadradri Kothagudem": ["Bhadradri Kothagudem", "Bhadrachalam", "Manuguru", "Yellandu"],
    "Hyderabad": ["Hyderabad", "Secunderabad", "GHMC", "Karimnagar"],
    "Jagtial": ["Jagtial", "Jagtial Town", "Kondagattu", "Sirsilla"],
    "Jangaon": ["Jangaon", "Jangaon Town", "Raipole", "Palakurthi"],
    "Jayashankar": ["Jayashankar", "Warangal Rural", "Jangaon", "Narmetta"],
    "Jogulamba": ["Jogulamba", "Alampur", "Malkapur", "Gadwal"],
    "Kamareddy": ["Kamareddy", "Kamareddy Town", "Banswada", "Bhiknoor"],
    "Karimnagar": ["Karimnagar", "Karimnagar Town", "Huzurabad", "Sircilla"],
    "Khammam": ["Khammam", "Khammam Town", "Yellandu", "Sathupalli"],
    "Komaram Bheem": ["Komaram Bheem", "Kumram Bheem", "Asifabad", "Chennur"],
    "Mahabubabad": ["Mahabubabad", "Mahabubabad Town", "Damaracherla", "Narsampet"],
    "Mahbubnagar": ["Mahbubnagar", "Mahbubnagar Town", "Gadwal", "Wanaparthy"],
    "Mancherial": ["Mancherial", "Mancherial Town", "Bellampalli", "Mandamarri"],
    "Medak": ["Medak", "Medak Town", "Sangareddy", "Narayanakhed"],
    "Medchal": ["Medchal", "Medchal-Malkajgiri", "Kukatpally", "Balanagar"],
    "Nagarkurnool": ["Nagarkurnool", "Nagarkurnool Town", "Achampet", "Kalwakurthy"],
    "Nalgonda": ["Nalgonda", "Nalgonda Town", "Suryapet", "Peddapalli"],
    "Nirmal": ["Nirmal", "Nirmal Town", "Bhainsa", "Mandal"],
    "Nizamabad": ["Nizamabad", "Nizamabad Town", "Bodhan", "Kamareddy"],
    "Peddapalli": ["Peddapalli", "Peddapalli Town", "Ramagundam", "Manthani"],
    "Rajanna Sircilla": ["Rajanna Sircilla", "Sircilla", "Vemulawada", "Choppadandi"],
    "Ranga Reddy": ["Ranga Reddy", "Ranga Reddy District", "Shamshabad", "Moinabad"],
    "Sangareddy": ["Sangareddy", "Sangareddy Town", "Patancheru", "Jinnaram"],
    "Siddipet": ["Siddipet", "Siddipet Town", "Gajwel", "Peddapalli"],
    "Suryapet": ["Suryapet", "Suryapet Town", "Nellipaka", "Huzurabad"],
    "Vikarabad": ["Vikarabad", "Vikarabad Town", "Parigi", "Peddemul"],
    "Wanaparthy": ["Wanaparthy", "Wanaparthy Town", "Gadwal", "Madhira"],
    "Warangal Rural": ["Warangal Rural", "Warangal", "Warangal Rural Town", "Jangaon"],
    "Warangal Urban": ["Warangal Urban", "Warangal", "Hanamkonda", "Kazipet"],
    "Yadadri Bhuvanagiri": ["Yadadri Bhuvanagiri", "Yadagirigutta", "Bhuvanagiri", "Raigir"],

    //Tripura
    "Dhalai": ["Dhalai", "Ambassa", "Manu", "Kailashahar"],
    "Gomati": ["Gomati", "Udaipur", "Kamalpur", "Karbook"],
    "Khowai": ["Khowai", "Khowai", "Teliamura", "Ramchandra Nagar"],
    "North Tripura": ["North Tripura", "Dharmanagar", "Panisagar", "Jamaipur"],
    "Sepahijala": ["Sepahijala", "Sonamura", "Bishalgarh", "Jirania"],
    "South Tripura": ["South Tripura", "Belonia", "Santirbazar", "Udaipur"],
    "Unakoti": ["Unakoti", "Kailashahar", "Dhalai", "Panchayet"],
    "West Tripura": ["West Tripura", "Agartala", "Jirania", "Tampu"],


    //Uttarakhand

    "Almora": ["Almora", "Bageshwar", "Ranikhet", "Dwarahat", "Kasi"],
    "Bageshwar": ["Bageshwar", "Kapkot", "Kanda", "Pindari"],
    "Chamoli": ["Chamoli", "Joshimath", "Gopeshwar", "Nandaprayag"],
    "Champawat": ["Champawat", "Tanakpur", "Pati"],
    "Dehradun": ["Dehradun", "Doiwala", "Rajpur", "Vikasnagar"],
    "Haridwar": ["Haridwar", "Rohru", "Laksar", "Jhabrera"],
    "Nainital": ["Nainital", "Haldwani", "Kashipur", "Rudrapur"],
    "Pauri": ["Pauri", "Pauri Garhwal", "Lansdowne", "Kotdwar"],
    "Pithoragarh": ["Pithoragarh", "Munsiyari", "Didihat", "Bhotia"],
    "Rudraprayag": ["Rudraprayag", "Ukhimath", "Kedarnath", "Guptkashi"],
    "Tehri": ["Tehri", "New Tehri", "Chamba", "Kandikhal"],
    "Udham Singh Nagar": ["Udham Singh Nagar", "Kichha", "Jaspur", "Rudrapur"],
    "Uttarkashi": ["Uttarkashi", "Bhatwari", "Gangotri", "Yamunotri"],






    //West Bangal

    "Bankura":["Bankura I","Bankura II","Barjora","Chhatna","Gangajalghati","Hirbandh","Indpur","Indus","Jaypur","Khatra","Kotulpur","Mejhia","Onda","Patrasayer","Raipur","Ranibundh","Saltora","Sarenga","Simlapal","Sonamukhi","Taldangra","Vishnupur"],
    "Barddhaman":["Ausgram I","Ausgram II","Barabani","Bhatar","Burdwan I","Burdwan II","Faridpur Durgapur","Galsi I","Galsi II","Jamalpur","Jamuria","Kalna I","Kalna II","Kanksa","Katwa I","Katwa II","Ketugram I","Ketugram II","Khandaghosh","Mangolkote","Manteswar","Memari I","Memari II","Ondal","Pandabeswar","Purbasthali I","Purbasthali II","Raina I","Raina II","Raniganj","Salanpur"],
    "Birbhum":["Bolpur Sriniketan","Dubrajpur","Illambazar","Khoyrasol","Labpur","Mayureswar I","Mayureswar II","Mohammad Bazar","Murarai I","Murarai II","Nalhati I","Nalhati II","Nanoor","Rajnagar","Rampurhat I","Rampurhat II","Sainthia","Suri I","Suri II"],
    "Dakshin Dinajpur":["Balurghat","Bansihari","Gangarampur","Harirampur","Hilli","Kumarganj","Kushmundi","Tapan"],
    "Darjiling":["Darjeeling Pulbazar","Gorubathan","Jorebunglow Sukiapokhri","Kalimpong I","Kalimpong II","Kharibari","Kurseong","Matigara","Mirik","Naxalbari","Phansidewa","Rangli Rangliot"],
    "Hawra":["Amta I","Amta II","Bagnan I","Bagnan II","Bally Jagachha","Domjur","Jagatballavpur","Panchla","Sankrail","Shyampur I","Shyampur II","Udaynarayanpur","Uluberia I","Uluberia II"],
    "Hugli":["Arambag","Balagarh","Chanditala I","Chanditala II","Chinsurah Magra","Dhaniakhali","Goghat I","Goghat II","Haripal","Jangipara","Khanakul I","Khanakul II","Pandua","Polba Dadpur","Pursura","Serampur Uttarpara","Singur","Tarakeswar"],
    "Jalpaiguri":["Alipurduar I","Alipurduar II","Dhupguri","Falakata","Jalpaiguri","Kalchini","Kumargram","Madarihat","Mal","Matiali","Maynaguri","Nagrakata","Rajganj"],
    "Koch Bihar":["Cooch Behar I","Cooch Behar II","Dinhata I","Dinhata II","Haldibari","Mathabhanga I","Mathabhanga II","Mekliganj","Sitai","Sitalkuchi","Tufanganj I","Tufanganj II"],
    "Kolkata":["Kolkata"],
    "Maldah":["Bamangola","Chanchal I","Chanchal II","English Bazar","Gazole","Habibpur","Harischandrapur I","Harischandrapur II","Kaliachak I","Kaliachak II","Kaliachak III","Maldah Old","Manikchak","Ratua I","Ratua II"],
    "Murshidabad":["Beldanga I","Beldanga II","Berhampore","Bhagawangola I","Bhagawangola II","Bharatpur I","Bharatpur II","Burwan","Domkal","Farakka","Hariharpara","Jalangi","Kandi","Khargram","Lalgola","Murshidabad Jiaganj","Nabagram","Nawda","Raghunathganj I","Raghunathganj II","Raninagar I","Raninagar II","Sagardighi","Samserganj","Suti I","Suti II"],
    "Nadia":["Chakdah","Chapra","Hanskhali","Haringhata","Kaliganj","Karimpur I","Karimpur II","Krishnaganj","Krishnagar I","Krishnagar II","Nabadwip","Nakashipara","Ranaghat I","Ranaghat II","Santipur","Tehatta I","Tehatta II"],
    "North Twenty Four Parganas":["Amdanga","Baduria","Bagda","Barasat I","Barasat II","Barrackpur I","Barrackpur II","Basirhat I","Basirhat II","Bongaon","Deganga","Gaighata","Habra I","Habra II","Haroa","Hasnabad","Hingalganj","Minakhan","Rajarhat","Sandeshkhali I","Sandeshkhali II","Swarupnagar"],
    "Paschim Medinipur":["Binpur I","Binpur II","Chandrakona I","Chandrakona II","Dantan I","Dantan II","Daspur I","Daspur II","Debra","Garbeta I","Garbeta II","Garbeta III","Ghatal","Gopiballavpur I","Gopiballavpur II","Jamboni","Jhargram","Keshiary","Keshpur","Kharagpur I","Kharagpur II","Midnapore","Mohanpur","Narayangarh","Nayagram","Pingla","Sabang","Salbani","Sankrail"],
    "Purba Medinipur":["Bhagawanpur I","Bhagawanpur II","Chandipur","Contai I","Contai III","Deshopran","Egra I","Egra II","Haldia","Khejuri I","Khejuri II","Kolaghat","Mahisadal","Moyna","Nanda Kumar","Nandigram I","Nandigram II","Panskura","Potashpur I","Potashpur II","Ramnagar I","Ramnagar II","Sahid Matangini","Sutahata","Tamluk"],
    "Puruliya":["Arsha","Bagmundi","Balarampur","Barabazar","Bundwan","Hura","Jaipur","Jhalda I","Jhalda II","Kashipur","Manbazar I","Manbazar II","Neturia","Para","Puncha","Purulia I","Purulia II","Raghunathpur I","Raghunathpur II","Santuri"],
    "South Twenty Four Parganas":["Baruipur","Basanti","Bhangar I","Bhangar II","Bishnupur I","Bishnupur II","Budge Budge I","Budge Budge II","Canning I","Canning II","Diamond Harbour I","Diamond Harbour II","Falta","Gosaba","Jaynagar I","Jaynagar II","Kakdwip","Kulpi","Kultali","Magrahat I","Magrahat II","Mandirbazar","Mathurapur I","Mathurapur II","Namkhana","Patharpratima","Sagar","Sonarpur","Thakurpukur Mahestola"],
    "Uttar Dinajpur":["Chopra","Goalpokhar I","Goalpokhar II","Hemtabad","Islampur","Itahar","Kaliaganj","Karandighi","Raiganj"],


    // Assam
    "Baksa": ["Barama", "Goreswar", "Jalah", "Tamulpur"],
    "Barpeta": ["Barpeta", "Bajali", "Barnagar", "Bhawanipur", "Chenga", "Gobardhana", "Kalgachia", "Mandia", "Paka Betbari", "Sarthebari", "Sarupeta"],
    "Biswanath": ["Biswanath", "Borgang", "Gohpur", "Helem", "Sotea"],
    "Bongaigaon": ["Boitamari", "Bongaigaon", "Dangtol", "Srijangram"],
    "Cachar": ["Barjalenga", "Borkhola", "Cachar Sadar", "Kalain", "Katigora", "Lakhipur", "Rajnagar", "Sonai"],
    "Charaideo": ["Mahura", "Mokokchung", "Sonari"],
    "Chirang": ["Bengtol", "Chirang", "Kajalgaon"],
    "Darrang": ["Dalgaon", "Kharupetia", "Patharighat", "Sipajhar"],
    "Dhemaji": ["Dhemaji", "Gogamukh", "Jonai", "Machkhowa"],
    "Dhubri": ["Agomani", "Bilasipara", "Bilasipara West", "Chapar", "Dhubri", "Golokganj", "South Salmara", "Gauripur"],
    "Dibrugarh": ["Barbaruah", "Dibrugarh East", "Joypur", "Khowang", "Lahoal", "Panitola", "Tengakhat", "Tingkhong"],
    "Goalpara": ["Balijana", "Dudhnoi", "Lakhipur", "Matia", "Rangjuli"],
    "Golaghat": ["Bokakhat", "Borpathar", "Dergaon", "Golaghat", "Khumtai", "Morongi", "Sarupathar"],
    "Hailakandi": ["Algapur", "Hailakandi", "Katlicherra", "Lala"],
    "Hojai": ["Doboka", "Hojai", "Lanka"],
    "Jorhat": ["Bhogamukh", "Jorhat East", "Jorhat West", "Majuli", "Mariani", "Teok", "Titabor"],
    "Kamrup Metropolitan": ["Guwahati", "Dispur"],
    "Kamrup (Rural)": ["Bezera", "Boko", "Chamaria", "Chandrapur", "Chhaygaon", "Dimoria", "Goroimari", "Hajo", "Kamrup Sadar", "North Guwahati", "Rampur", "Rangia", "Tihu"],
    "Karbi Anglong": ["Bokajan", "Diphu", "Hamren"],
    "Karimganj": ["Badarpur", "Karimganj", "Nilambazar", "Patharkandi", "Ramkrishna Nagar"],
    "Kokrajhar": ["Bhowraguri", "Chirang", "Gossaigaon", "Kachugaon", "Kokrajhar", "Serfanguri"],
    "Lakhimpur": ["Bihpuria", "Ghilamara", "Lakhimpur", "Narayanpur", "Nowboicha"],
    "Majuli": ["Ujani Majuli", "Lower Majuli"],
    "Morigaon": ["Bhuragaon", "Laharighat", "Mayong", "Morigaon"],
    "Nagaon": ["Bajiagaon", "Barhampur", "Batadraba", "Dhing", "Juria", "Kampur", "Kaliabor", "Khatowal", "Nagaon", "Pachim Kaliabor", "Raha"],
    "Nalbari": ["Barkhetri", "Belsor", "Ghograpar", "Nalbari", "Pachim Nalbari"],
    "Dima Hasao": ["Umrangso", "Maibang", "Mahur", "Harangajao"],
    "Sivasagar": ["Amguri", "Demow", "Gaurisagar", "Nazira", "Sivasagar", "Ujan Bazar"],
    "Sonitpur": ["Balipara", "Barchalla", "Biswanath", "Dhekiajuli", "Gohpur", "Jamugurihat", "Tezpur"],
    "South Salmara Mankachar": ["Fakirganj", "Hatsingimari", "Kushakata", "Mankachar"],
    "Tinsukia": ["Chapakhowa", "Doomdooma", "Hapjan", "Itakhuli", "Kakopathar", "Makum", "Margherita", "Saikhowa", "Tengapani", "Tinsukia"],
    "Udalguri": ["Bhergaon", "Harisinga", "Kalaigaon", "Mazhbat", "Rowta", "Udalguri"],
    "West Karbi Anglong": ["Baithalangso", "Dongkamokam", "Rongkhang"],



    // Andhra Pradesh

    "Anantapur": ["Atmakur", "Bathalapalli", "Bommanahal", "Bukkarayasamudram", "Chennekothapalli", "D.Hirehal", "Garladinne", "Gooty", "Gummagatta", "Kalyandurg", "Kambadur", "Kundurpi", "Madakasira", "Mudigubba", "Nallamada", "Parigi", "Peddapappur", "Peddavadugur", "Putlur", "Ramagiri", "Raptadu", "Roddam", "Settur", "Singanamala", "Somandepalle", "Tadimarri", "Tadipatri", "Talupula", "Uravakonda", "Vidapanakal", "Yellanur"],
    "Chittoor": ["Baireddipalle", "Bangarupalem", "Chandragiri", "Chittoor", "Gangadhara Nellore", "Gudipala", "Irala", "K.V.B.Puram", "Kalikiri", "Kambhamvaripalle", "Kangundi", "Karvetinagar", "Kuppam", "Nagari", "Nindra", "Palamaner", "Pakala", "Peddamandyam", "Peddapanjani", "Punganur", "Pulicherla", "Ramakuppam", "Renigunta", "Rompicherla", "S.R.Puram", "Santhipuram", "Satyavedu", "Sodam", "Somala", "Srikalahasti", "Thamballapalle", "Thottambedu", "V.Kota", "Vedurukuppam", "Yerpedu"],
    "East Godavari": ["Addateegala", "Allavaram", "Amalapuram", "Ambajipeta", "Anaparthy", "Atreyapuram", "Bikkavolu", "Chintur", "Devipatnam", "Gokavaram", "Gollaprolu", "I.Polavaram", "Jaggampeta", "Kadali", "Kadiam", "Kajuluru", "Kapileswarapuram", "Karapa", "Katheru", "Kirlampudi", "Korukonda", "Kothapeta", "Mandapeta", "Maredumilli", "Mummidivaram", "Nallajerla", "P.Gannavaram", "Peddapuram", "Rajanagaram", "Rangampeta", "Rayavaram", "Razole", "Routhulapudi", "Samalkota", "Sankavaram", "Sarpavaram", "Seethanagaram", "Thallarevu", "Tuni", "Y.Ramavaram"],
    "Guntur": ["Achampet", "Amaravathi", "Atchampet", "Bapatla", "Bellamkonda", "Bhattiprolu", "Chebrole", "Chilakaluripet", "Dachepalli", "Duggirala", "Durgi", "Gurazala", "Kollipara", "Krosuru", "Machavaram", "Mangalagiri", "Muppalla", "Nadendla", "Narsaraopet", "Nekarikallu", "Nidumolu", "Pedakakani", "Pedanandipadu", "Piduguralla", "Ponnur", "Prathipadu", "Rajupalem", "Repalle", "Rompicherla", "Sattenapalli", "Tenali", "Thullur", "Vemuru", "Vinukonda", "Veldurthi"],
    "Kadapa": ["Atlur", "Badvel", "Brahmamgarimatham", "Chakrayapet", "Chinnamandem", "Chitvel", "Duvvur", "Gopavaram", "Jammalamadugu", "Kadapa", "Kalasapadu", "Kamalapuram", "Kandimallayapalle", "Kasinayapalle", "Khajipet", "Kodur", "Lakkireddipalle", "Lingala", "Muddanur", "Mylavaram", "Nandalur", "Obulavaripalle", "Porumamilla", "Proddatur", "Pullampeta", "Rajampet", "Ramapuram", "Sidhavatam", "Sunnipenta", "T Sundupalle", "Veeraballe", "Vempalle", "Vontimitta"],
    "Krishna": ["Agiripalli", "Bantumilli", "Bapulapadu", "Chatrai", "G.Konduru", "Gannavaram", "Gudiwada", "Gudlavalleru", "Ibrahimpatnam", "Jaggayyapeta", "Kaikaluru", "Kanchikacherla", "Koduru", "Kruthivennu", "Machilipatnam", "Mopidevi", "Mudinepalli", "Movva", "Mylavaram", "Nagayalanka", "Nandigama", "Nandivada", "Nuzvid", "Pamarru", "Pedana", "Pedaparupudi", "Penamaluru", "Reddigudem", "Tiruvuru", "Unguturu", "Vatsavai", "Veerullapadu", "Vijayawada Rural", "Vijayawada Urban"],
    "Kurnool": ["Adoni", "Alur", "Aspari", "Banaganapalle", "C.Belagal", "Chagalamarri", "Chippagiri", "Devanakonda", "Dhone", "Emmiganur", "Gadivemula", "Gonegandla", "Gospadu", "Halaharvi", "Holagunda", "Jupadu Bungalow", "Kodumur", "Koilkuntla", "Kolimigundla", "Kosigi", "Kowthalam", "Kurnool", "Maddikera", "Mantralayam", "Nandavaram", "Nandyal", "Owk", "Pamulapadu", "Panyam", "Peapully", "Pedda Kadubur", "Rudravaram", "Sanjeevayyanagarm", "Srisailam", "Tuggali", "Uyyalawada", "Veldurthi", "Velgodu"],
    "Prakasam": ["Addanki", "Ballikurava", "Bestavaripeta", "Cumbum", "Chandarlapadu", "Chirala", "Donakonda", "Darsi", "Giddalur", "Hanumanthunipadu", "Inkollu", "J Panguluru", "Kanigiri", "Kandukur", "Komarolu", "Konakana Metla", "Korispadu", "Kothapatnam", "Kurichedu", "Maddipadu", "Markapur", "Marripudi", "Martur", "Naguluppalapadu", "Ongole", "Pamur", "Parchur", "Podili", "Pullalacheruvu", "Racherla", "Santhamaguluru", "Singarayakonda", "Tangutur", "Tarlupadu", "Tripurantakam", "Veligandla", "Vetapalem", "Yerragondapalem"],
    "Nellore": ["Allur", "Anantasagaram", "Atmakur", "Bogole", "Buchireddipalem", "Chejerla", "Dagadarthi", "Duttalur", "Indukurpet", "Jaladanki", "Kaligiri", "Kaluvoya", "Kavali", "Kodavaluru", "Kondapuram", "Kothur", "Manubolu", "Marripadu", "Muthukur", "Nellore Rural", "Nellore Urban", "Podalakur", "Rapur", "Sangam", "Seetharamapuram", "Sullurupeta", "Thotapalligudur", "Tirumala", "Udayagiri", "Venkatachalam", "Venkatagiri", "Vijayapuram", "Vinjamur"],
    "Srikakulam": ["Amadalavalasa", "Burja", "Etcherla", "Gara", "Ganguvarisigadam", "Hiramandalam", "Ichchapuram", "Kanchili", "Kaviti", "Kothuru", "L.N.Peta", "Laveru", "Mandasa", "Meliaputti", "Nandigam", "Narasannapeta", "Palasa", "Palakonda", "Patapatnam", "Polaki", "Ranastalam", "Santhabommali", "Saravakota", "Seethampeta", "Sompeta", "Tekkali", "Vajrapukothuru", "Vangara"],
    "Visakhapatnam": ["Anakapalle", "Anandapuram", "Araku Valley", "Atchutapuram", "Bheemunipatnam", "Cheedikada", "Chintapalle", "Chodavaram", "Devarapalle", "Dumbriguda", "Gajapathinagaram", "Gopalapatnam", "K.Kotapadu", "Kasimkota", "Kasimkota", "Kovvur", "Madugula", "Makavarapalem", "Munagapaka", "Narsipatnam", "Nathavaram", "Paderu", "Paravada", "Payakaraopeta", "Pedabayalu", "Pedagantyada", "Pendurthi", "Ravikamatham", "Rolugunta", "Sabbavaram", "S.Kota", "V.Madugula", "Visakhapatnam Rural", "Visakhapatnam Urban"],
    "Vizianagaram": ["Badangi", "Bondapalle", "Cheepurupalle", "Dattirajeru", "Gajapathinagaram", "Garugubilli", "Gurla", "Jami", "Kothavalasa", "Kurupam", "Lakkavarapukota", "Mentada", "Merakamudidam", "Nellimarla", "Pachipenta", "Parvathipuram", "Pusapatirega", "Ramabhadrapuram", "Salur", "Seethanagaram", "Srungavarapukota", "Therlam", "Veeraghattam", "Vepada", "Vizianagaram"],
    "West Godavari": ["Achanta", "Attili", "Bhimadole", "Bhimavaram", "Buttayagudem", "Chagallu", "Chintalapudi", "Devarapalle", "Denduluru", "Dwaraka Tirumala", "Eluru", "Ganapavaram", "Iragavaram", "Jangareddygudem", "Kalla", "Kamavarapukota", "Kaikaluru", "Kalidindi", "Kalla", "Kovvur", "Nallajerla", "Nidadavole", "Palakoderu", "Palakollu", "Pedapadu", "Pedavegi", "Penugonda", "Poduru", "Polavaram", "Rangampeta", "Tadepalligudem", "T Narasapuram", "Tanuku", "Unguturu", "Vallur", "Yelamanchili", "Yernagudem"],



    "Y S R": ["Atlur", "B Kodur", "Badvel", "Brahmamgarimattam", "Chakrayapet", "Chapad", "Chennur", "Chinnamandem", "Chinthakommadinne", "Chitvel", "Duvvur", "Galiveedu", "Gopavaram", "Jammalamadugu", "Kadapa", "Kalasapadu", "Kamalapuram", "Khajipet", "Kodur", "Kondapuram", "Lakkireddipalle", "Lingala", "Muddanur", "Mylavaram", "Nandalur", "Obulavaripalle", "Peddamudium", "Penagalur", "Pendlimarri", "Porumamilla", "Proddatur", "Pulivendla", "Pullampeta", "Rajampet", "Rajupalem", "Ramapuram", "Rayachoti", "S Mydukur", "Sambepalle", "Sidhout", "Simhadripuram", "Sri Avadhutha Kasinayana", "T Sundupalle", "Thondur", "Vallur", "Veeraballe", "Veerapunayunipalle", "Vempalle", "Vemula", "Vontimitta", "Yerraguntla"],


    //bihar
    "Araria":["Araria","Bhargama","Forbesganj","Jokihat","Kursakatta","Narpatganj","Palasi","Raniganj","Sikti"],
    "Arwal":["Arwal","Kaler","Karpi","Kurtha","Sonbhadra Banshi Suryapur"],
    "Aurangabad":["Aurangabad","Barun","Daudnagar","Deo","Goh","Haspura","Kutumba","Madanpur","Nabinagar","Obra","Rafiganj"],
    "Banka":["Amarpur","Banka","Barahat","Bausi","Belhar","Chanan","Dhuraiya","Katoria","Phulidumar","Rajaun","Shambhuganj"],
    "Begusarai":["Bachhwara","Bakhri","Balia","Barauni","Begusarai","Bhagwanpur","Birpur","Cheria Bariarpur","Chhorahi","Dandari","Garhpura","Khudabandpur","Mansurchak","Matihani","Naokothi","Sahebpur Kamal","Shamho Akha Kurha","Teghra"],
    "Bhagalpur":["Bihpur","Colgong","Gopalpur","Goradih","Ismailpur","Jagdishpur","Kharik","Narayanpur","Nathnagar","Naugachhia","Pirpainti","Rangra Chowk","Sabour","Shahkund","Sonhaula","Sultanganj"],
    "Bhojpur":["Agiaon","Arrah","Barhara","Behea","Charpokhari","Garhani","Jagdishpur","Koilwar","Piro","Sahar","Sandesh","Shahpur","Tarari","Udwant Nagar"],
    "Buxar":["Barhampur","Buxar","Chakki","Chaugain","Chausa","Dumraon","Itarhi","Kesath","Nawanagar","Rajpur","Simri"],
    "Darbhanga":["Alinagar","Bahadurpur","Baheri","Benipur","Biraul","Darbhanga","Ghanshyampur","Gora Bauram","Hanumannagar","Hayaghat","Jale","Keotiranway","Kiratpur","Kusheshwar Asthan","Kusheshwar Asthan Purbi","Manigachhi","Singhwara","Tardih"],
    "Gaya":["Amas","Atri","Banke Bazar","Barachatti","Belaganj","Bodh Gaya","Dobhi","Dumaria","Fatehpur","Gaya Town C D Block","Guraru","Gurua","Imamganj","Khizirsarai","Konch","Manpur","Mohanpur","Muhra","Neem Chak Bathani","Paraiya","Sherghati","Tan Kuppa","Tikari","Wazirganj"],
    "Gopalganj":["Baikunthpur","Barauli","Bhorey","Bijaipur","Gopalganj","Hathua","Katiya","Kuchaikote","Manjha","Pach Deuri","Phulwaria","Sidhwalia","Thawe","Uchkagaon"],
    "Jamui":["Barhat","Chakai","Gidhaur","Islamnagar Aliganj","Jamui","Jhajha","Khaira","Lakshmipur","Sikandra","Sono"],
    "Jehanabad":["Ghoshi","Hulasganj","Jehanabad","Kako","Makhdumpur","Modanganj","Ratni Faridpur"],
    "Kaimur":["Adhaura","Bhabua","Bhagwanpur","Chainpur","Chand","Durgawati","Kudra","Mohania","Nuaon"],
    "Katihar":["Amdabad","Azamnagar","Balrampur","Barari","Barsoi","Dandkhora","Falka","Hasanganj","Kadwa","Katihar","Korha","Kursela","Manihari","Mansahi","Pranpur","Sameli"],
    "Khagaria":["Alauli","Beldaur","Chautham","Gogri","Khagaria","Mansi","Parbatta"],
    "Kishanganj":["Bahadurganj","Dighalbank","Kishanganj","Kochadhamin","Pothia","Terhagachh","Thakurganj"],
    "Lakhisarai":["Barahiya","Chanan","Halsi","Lakhisarai","Pipariya","Ramgarh Chowk","Surajgarha"],
    "Madhepura":["Alamnagar","Bihariganj","Chausa","Gamharia","Ghailarh","Gwalpara","Kishanganj","Kumarkhand","Madhepura","Murliganj","Puraini","Shankarpur","Singheshwar"],
    "Madhubani":["Andhratharhi","Babubarhi","Basopatti","Benipatti","Bisfi","Ghoghardiha","Harlakhi","Jainagar","Jhanjharpur","Kaluahi","Khajauli","Ladania","Lakhnaur","Laukaha","Laukahi","Madhepur","Madhubani","Madhwapur","Pandaul","Phulparas","Rajnagar"],
    "Munger":["Asarganj","Bariarpur","Dharhara","Jamalpur","Kharagpur","Munger","Sangrampur","Tarapur","Tetiha Bambor"],
    "Muzaffarpur":["Aurai","Bandra","Baruraj","Bochaha","Dholi","Gaighat","Kanti","Katra","Kurhani","Marwan","Minapur","Musahri","Paroo","Sahebganj","Sakra","Saraiya"],
    "Nalanda":["Asthawan","Ben","Bihar","Bind","Chandi","Ekangarsarai","Giriak","Harnaut","Hilsa","Islampur","Karai Parsurai","Katrisarai","Nagar Nausa","Noorsarai","Parbalpur","Rahui","Rajgir","Sarmera","Silao","Tharthari"],
    "Nawada":["Akbarpur","Gobindpur","Hisua","Kashi Chak","Kawakol","Meskaur","Nardiganj","Narhat","Nawada","Pakribarawan","Rajauli","Roh","Sirdala","Warisaliganj"],
    "Pashchim Champaran":["Bagaha","Bairia","Bettiah","Bhitaha","Chanpatia","Gaunaha","Jogapatti","Lauriya","Madhubani","Mainatanr","Majhaulia","Narkatiaganj","Nautan","Piprasi","Ramnagar","Sidhaw","Sikta","Thakrahan"],
    "Patna":["Athmalgola","Bakhtiarpur","Barh","Belchhi","Bihta","Bikram","Daniawan","Dhanarua","Dinapur Cum Khagaul","Dulhin Bazar","Fatwah","Ghoswari","Khusrupur","Maner","Masaurhi","Mokameh","Naubatpur","Paliganj","Pandarak","Patna Rural","Phulwari","Punpun","Sampatchak"],
    "Purba Champaran":["Adapur","Areraj","Banjaria","Bankatwa","Chakia","Chiraia","Dhaka","Ghorasahan","Harsidhi","Kalyanpur","Kesaria","Kotwa","Madhuban","Mehsi","Motihari","Narkatia","Paharpur","Pakri Dayal","Patahi","Phenhara","Piprakothi","Ramgarhwa","Raxaul","Sangrampur","Sugauli","Tetaria","Turkaulia"],
    "Purnia":["Amour","Baisa","Baisi","Banmankhi","Barhara","Bhawanipur","Dagarua","Dhamdaha","Jalalgarh","Kasba","Krityanand Nagar","Purnia East","Rupauli","Srinagar"],
    "Rohtas":["Akorhi Gola","Bikramganj","Chenari","Dawath","Dehri","Dinara","Karakat","Kargahar","Kochas","Nasriganj","Nauhatta","Nokha","Rajpur","Rohtas","Sanjhauli","Sasaram","Sheosagar","Suryapura","Tilouthu"],
    "Saharsa":["Banma Itahri","Kahara","Mahishi","Nauhatta","Patarghat","Salkhua","Satar Kataiya","Saur Bazar","Simri Bakhtiarpur","Sonbarsa"],
    "Samastipur":["Bibhutpur","Bithan","Dalsinghsarai","Hasanpur","Kalyanpur","Khanpur","Mohanpur","Mohiuddinagar","Morwa","Patori","Pusa","Rosera","Samastipur","Sarairanjan","Shivaji Nagar","Singhia","Tajpur","Ujiarpur","Vidyapati Nagar","Warisnagar"],
    "Saran":["Amnour","Baniapur","Chapra","Dariapur","Dighwara","Ekma","Garkha","Ishupur","Jalalpur","Lahladpur","Maker","Manjhi","Marhaura","Mashrakh","Nagra","Panapur","Parsa","Revelganj","Sonepur","Taraiya"],
    "Sheikhpura":["Ariari","Barbigha","Chewara","Ghat Kusumbha","Sheikhpura","Shekhopur Sarai"],
    "Sheohar":["Dumri Katsari","Piprarhi","Purnahiya","Sheohar","Tariani Chowk"],
    "Sitamarhi":["Bairgania","Bajpatti","Bathnaha","Belsand","Bokhara","Charaut","Dumra","Majorganj","Nanpur","Parihar","Parsauni","Pupri","Riga","Runisaidpur","Sonbarsa","Suppi","Sursand"],
    "Siwan":["Andar","Barharia","Basantpur","Bhagwanpur Hat","Darauli","Daraundha","Goriakothi","Guthani","Hasanpura","Hussainganj","Lakri Nabiganj","Maharajganj","Mairwa","Nautan","Pachrukhi","Raghunathpur","Siswan","Siwan","Ziradei"],
    "Supaul":["Basantpur","Chhatapur","Kishanpur","Marauna","Nirmali","Pipra","Pratapganj","Raghopur","Saraigarh Bhaptiyahi","Supaul","Tribeniganj"],
    "Vaishali":["Bhagwanpur","Bidupur","Chehra Kalan","Desri","Goraul","Hajipur","Jandaha","Lalganj","Mahnar","Mahua","Patepur","Paterhi Belsar","Raghopur","Raja Pakar","Sahdai Buzurg","Vaishali"],


    // //bihar updated
    //     "Araria": ["Araria", "Falka", "Forbesganj", "Jokihat", "Kursakanta", "Raniganj", "Sikti", "Palasi"],
    //     "Arwal": ["Arwal", "Karpi", "Kaler", "Kurtha"],
    //     "Aurangabad": ["Aurangabad", "Barun", "Daudnagar", "Goh", "Kutumba", "Nabinagar", "Rafiganj"],
    //     "Banka": ["Banka", "Amarpur", "Barahat", "Belhar", "Dhuraiya", "Katoria", "Rajaun", "Shambhuganj"],
    //     "Begusarai": ["Begusarai", "Bachhwara", "Bakhri", "Bhagwanpur", "Birpur", "Cheria Bariarpur", "Dandari", "Garhpura", "Khudabandpur", "Mansurchak", "Matihani", "Nawada", "Sahebpur Kamal", "Teghra"],
    //     "Bhagalpur": ["Bhagalpur", "Bihpur", "Colgong (Kahalgaon)", "Goradih", "Ismailpur", "Jagdishpur", "Nathnagar", "Narayanpur", "Sabour", "Sultanganj", "Shahkund"],
    //     "Bhojpur": ["Arrah", "Agiaon", "Barhara", "Charpokhari", "Garhani", "Jagdishpur", "Koilwar", "Piro", "Sahar", "Sandesh", "Tarari", "Udwantnagar"],
    //     "Buxar": ["Buxar", "Chausa", "Dumraon", "Itarhi", "Kesath", "Nawanagar", "Rajpur", "Simri"],
    //     "Darbhanga": ["Darbhanga", "Alinagar", "Bahadurpur", "Benipur", "Biraul", "Ghanshyampur", "Hayaghat", "Jale", "Keoti", "Kusheshwar Asthan", "Manigachhi", "Singhwara", "Tardih"],
    //     "East Champaran": ["Motihari", "Areraj", "Banjariya", "Chakia", "Dhaka", "Harsidhi", "Kesaria", "Kotwa", "Madhuban", "Mehsi", "Pakaridayal", "Patahi", "Phenhara", "Raxaul", "Sangrampur", "Sugauli", "Tetariya", "Turkaulia"],
    //     "Gaya": ["Gaya", "Atri", "Barachatti", "Bodh Gaya", "Dumaria", "Fatehpur", "Gurua", "Imamganj", "Khizarsarai", "Manpur", "Mohra", "Sherghati", "Tekari"],
    //     "Gopalganj": ["Gopalganj", "Baikunthpur", "Barauli", "Bhore", "Hathua", "Kuchaikote", "Manjha", "Sidhwalia", "Thawe", "Uchkagaon"],
    //     "Jamui": ["Jamui", "Chakai", "Gidhaur", "Jhajha", "Khaira", "Lakshmipur", "Sikandra"],
    //     "Jehanabad": ["Jehanabad", "Ghoshi", "Hulasganj", "Makhdumpur", "Modanganj", "Kako"],
    //     "Kaimur": ["Bhabua", "Adhaura", "Chandan", "Durgawati", "Kudra", "Mohania", "Ramgarh"],
    //     "Katihar": ["Katihar", "Amdabad", "Barari", "Barsoi", "Dandkhora", "Falka", "Korha", "Manihari", "Pranpur", "Sameli"],
    //     "Khagaria": ["Khagaria", "Alauli", "Beldaur", "Chautham", "Gogri", "Parbatta"],
    //     "Kishanganj": ["Kishanganj", "Bahadurganj", "Dighalbank", "Kochadhaman", "Pothia", "Terhagachh"],
    //     "Lakhisarai": ["Lakhisarai", "Barahiya", "Chanan", "Halsi", "Pipariya", "Ramgarh Chowk", "Surajgarha"],
    //     "Madhepura": ["Madhepura", "Alamnagar", "Bihariganj", "Chausa", "Gwalpara", "Kumarkhand", "Murliganj", "Shankarpur", "Singheshwar"],
    //     "Madhubani": ["Madhubani", "Andhratharhi", "Babubarhi", "Basopatti", "Benipatti", "Bisfi", "Ghoghardiha", "Jainagar", "Jhanjharpur", "Khajauli", "Ladania", "Laukaha", "Laukahi", "Pandaul", "Phulparas", "Rahika"],
    //     "Munger": ["Munger", "Asarganj", "Barhiya", "Dharhara", "Haveli Kharagpur", "Jamalpur", "Kharagpur", "Sangrampur", "Tetiha Bambor"],
    //     "Muzaffarpur": ["Muzaffarpur", "Aurai", "Bochaha", "Gaighat", "Katra", "Kanti", "Kurhani", "Marwan", "Minapur", "Motipur", "Paroo", "Saraiya"],
    //     "Nalanda": ["Nalanda", "Asthawan", "Bihar Sharif", "Ben", "Chandi", "Ekangarsarai", "Harnaut", "Hilsa", "Islampur", "Parwalpur", "Rajgir", "Silao", "Tharthari"],
    //     "Nawada": ["Nawada", "Akashe", "Govindpur", "Hisua", "Kawakol", "Pakribarawan", "Rajauli", "Roh", "Sirdala", "Warisaliganj"],
    //     "Patna": ["Patna", "Bakhtiyarpur", "Barh", "Bikram", "Danapur", "Dhanarua", "Fatuha", "Khusrupur", "Maner", "Masaurhi", "Naubatpur", "Paliganj", "Phulwarisharif", "Punpun", "Sampatchak"],
    //     "Purnia": ["Purnia", "Amour", "Baisa", "Baisi", "Banmankhi", "Barhara", "Dagarua", "Dhamdaha", "Jalalgarh", "Kasba", "K. Nagar"],
    //     "Rohtas": ["Rohtas", "Akhorigola", "Bikramganj", "Chenari", "Dehri", "Dinara", "Karakat", "Kargahar", "Nokha", "Sasaram", "Shivsagar", "Tilouthu"],
    //     "Saharsa": ["Saharsa", "Banma Itahri", "Kahara", "Mahishi", "Nauhatta", "Patarghat", "Saur Bazar", "Simri Bakhtiarpur", "Sonbarsa"],
    //     "Samastipur": ["Samastipur", "Bibhutipur", "Hasanpur", "Kalyanpur", "Mohanpur", "Patori", "Rosera", "Shivajinagar", "Tajpur", "Ujiarpur", "Warisnagar"],
    //     "Saran": ["Saran", "Amnour", "Baniapur", "Chapra", "Dariapur", "Ekma", "Garkha", "Isuapur", "Jalalpur", "Lahladpur", "Marhaura", "Maker", "Manjhi", "Panapur", "Parsa", "Revelganj", "Sonepur", "Taraiya"],
    //     "Sheikhpura": ["Sheikhpura", "Ariari", "Barbigha", "Chewara", "Ghat Kusumbha", "Sheikhopur Sarai"],
    //     "Sheohar": ["Sheohar", "Dumri Katsari", "Piprahi", "Purnahiya", "Tariani"],
    //     "Sitamarhi": ["Sitamarhi", "Bajpatti", "Bathnaha", "Belsand", "Dumra", "Majorganj", "Parihar", "Pupri", "Riga", "Runni Saidpur", "Sursand"],
    //     "Siwan": ["Siwan", "Barharia", "Bhagwanpur Hat", "Darauli", "Duraundha", "Goriakothi", "Guthani", "Hasanpura", "Lakri Nabiganj", "Mairwa", "Maharajganj", "Nautan", "Pachrukhi", "Raghunathpur", "Siwan Sadar", "Ziradei"],
    //     "Supaul": ["Supaul", "Bhaptiyahi", "Chhatapur", "Nirmali", "Pipra", "Pratapganj", "Raghopur", "Tribeniganj"],
    //     "Vaishali": ["Vaishali", "Bhagwanpur", "Bidupur", "Desari", "Goraul", "Hajipur", "Jandaha", "Lalganj", "Mahnar", "Patepur", "Raghunathpur", "Rajapakar", "Sahdai Buzurg"],
    //     "West Champaran": ["Bettiah", "Bagaha", "Bairia", "Chanpatia", "Gaunaha", "Lauriya", "Mainatand", "Manuapul", "Narkatiaganj", "Nautan", "Ramnagar", "Sikta", "Thakaraha"],
    

    //    Arunachal Pradesh

    "Anjaw": ["Chaglagam", "Goiliang", "Hawai", "Hayuliang", "Kibithoo", "Manchal", "Metengliang", "Walong"],
    "Changlang": ["Bordumsa", "Changlang", "Diyun", "Jairampur", "Kharsang", "Khimiyong", "Lyngok Longtoi", "Manmao", "Miao", "Nampong", "Namtok", "Renuk", "Tikhak Rima Putok", "Vijoynagar", "Yatdam"],
    "Dibang Valley": ["Anelih", "Anini", "Etalin", "Kronli", "Mipi"],
    "East Kameng": ["Bameng", "Chayangtajo", "Dissing Passo", "Gyawe Purang", "Khenewa", "Lada", "Pakke Kessang", "Pipu Dipu", "Pizirang", "Richukrong", "Sawa", "Seijosa", "Seppa"],
    "East Siang": ["Bilat", "Boleng", "Kebang", "Kora", "Koyu", "Mebo", "Namsing", "Nari", "New Seren", "Pangin", "Pasighat", "Rebo Perging", "Riga", "Ruksin", "Sille Oyan"],
    "Kurung Kumey": ["Chambang", "Damin", "Gangte", "Koloriang", "Longding Koling", "Nyapin", "Palin", "Parsi Parlo", "Phassang", "Sangram", "Sarli", "Tali", "Tarak Lengdi", "Yangte"],
    "Lohit": ["Chongkham", "Lathao", "Lekang", "Namsai", "Piyong", "Sunpura", "Tezu", "Wakro"],
    "Lower Dibang Valley": ["Dambuk", "Desali", "Hunli", "Koronu", "Roing", "Tinali"],
    "Lower Subansiri": ["Dollungmukh", "Kamporijo", "Old Ziro", "Pistana", "Raga", "Yachuli", "Yazali", "Ziro"],
    "Papum Pare": ["Balijan", "Banderdawa", "Doimukh", "Gumto", "Itanagar", "Kakoi", "Kimin", "Leporiang", "Mengio", "Naharlagun", "Parang", "Sagalee", "Sangdupota", "Taraso", "Toru"],
    "Tawang": ["Bongkhar", "DUDUNGHAR", "Jang", "KITPI CIRCLE", "Lhou", "LUMLA", "MUKTO CIRCLE", "TAWANG CIRCLE", "Thingbu", "Zemithang"],
    "Tirap": ["Dadam", "Kanubari", "Khonsa", "Laju", "Lawnu", "Longding", "Namsang", "Pangchao", "Pumao", "Soha", "Wakka"],
    "Upper Siang": ["Geku", "Gelling", "Jengging", "Katan", "Mariyang", "Migging", "Mopom", "Palling", "Singa", "Tuting", "Yingkiong"],
    "Upper Subansiri": ["Baririjo", "Chetam", "Daporijo", "Dumporijo", "Giba", "Gite Ripa", "Gussar", "Limeking", "Maro", "Nacho", "Payeng", "Puchi Geko", "Siyum", "Taksing", "Taliha"],
    "West Kameng": ["Balemu", "Bhalukpong", "Bomdila", "Dirang", "Jamiri", "Kalaktang", "Kamengbari Doimara", "Nafra", "Rupa", "Shergaon", "Singchung", "Thembang", "Thrizino"],
    "West Siang": ["Aalo", "Bagra", "Basar", "Darak", "Daring", "Gensi", "Jomlo Mobuk", "Kamba", "Kangku", "Kaying", "Likabali", "Liromoba", "Mechuka", "Monigong", "Payum", "Pidi", "Rumgong", "Sibe", "Tato", "Tirbin", "Yomcha"],
    "Itanagar": ["Itanagar"]

}


const IndianDistrict = {
    "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Kadapa", "Krishna", "Kurnool", "Prakasam", "Nellore", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari"],
    "Arunachal Pradesh": ["Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Kra Daadi", "Kurung Kumey", "Lohit", "Longding", "Lower Dibang Valley", "Lower Subansiri", "Namsai", "Papum Pare", "Siang", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang", "Itanagar"],
    "Assam": ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup Metropolitan", "Kamrup (Rural)", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Dima Hasao", "Sivasagar", "Sonitpur", "South Salmara Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong"],
    "Bihar": ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"],
    "Chhattisgarh": ["Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Janjgir Champa", "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Koriya", "Mahasamund", "Mungeli", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur", "Surguja"],
    "Goa": ["North Goa", "South Goa"],
    "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
    "Haryana": ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Mewat", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"],
    "Himachal Pradesh": ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"],
    "Jammu and Kashmir": ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kargil", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Leh", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
    "Jharkhand": ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahebganj", "Seraikela Kharsawan", "Simdega", "West Singhbhum"],
    "Karnataka": ["Bagalkot", "Bangalore Rural", "Bangalore Urban", "Belgaum", "Bellary", "Bidar", "Vijayapura", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Gulbarga", "Hassan", "Haveri", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysore", "Raichur", "Ramanagara", "Shimoga", "Tumkur", "Udupi", "Uttara Kannada", "Yadgir"],
    "Kerala": ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"],
    "Madhya Pradesh": ["Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna",
        "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"],
    "Maharashtra": ["Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"],
    "Manipur": ["Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"],
    "Meghalaya": ["East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "North Garo Hills", "Ri Bhoi", "South Garo Hills", "South West Garo Hills", "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"],
    "Mizoram": ["Aizawl", "Champhai", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip", "Aizawl", "Champhai", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saiha", "Serchhip"],
    "Nagaland": ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"],
    "Odisha": ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Debagarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur", "Sundergarh"],
    "Punjab": ["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Firozpur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga", "Mohali", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sangrur", "Shaheed Bhagat Singh Nagar", "Tarn Taran"],
    "Rajasthan": ["Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Ganganagar", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Tonk", "Udaipur"],
    "Sikkim": ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
    "Tamil Nadu": ["Ariyalur", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kanchipuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Salem", "Sivaganga", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
    "Telangana": ["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar", "Jogulamba", "Kamareddy", "Karimnagar", "Khammam", "Komaram Bheem", "Mahabubabad", "Mahbubnagar", "Mancherial", "Medak", "Medchal", "Nagarkurnool", "Nalgonda", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Ranga Reddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"],
    "Tripura": ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
    "Uttar Pradesh": ["Agra", "Aligarh", "Allahabad", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah", "Faizabad", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
    "Uttarakhand": ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri", "Pithoragarh", "Rudraprayag", "Tehri", "Udham Singh Nagar", "Uttarkashi"],
    "West Bengal": ["Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur", "Purba Bardhaman", "Purba Medinipur", "Purulia", "South 24 Parganas", "Uttar Dinajpur"],
    "Andaman and Nicobar Islands": ["Nicobar", "North Middle Andaman", "South Andaman"],
    "Chandigarh": ["Chandigarh"],
    "Dadra and Nagar Haveli": ["Dadra Nagar Haveli"],
    "Daman and Diu": ["Daman", "Diu"],
    "Delhi": ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
    "Lakshadweep": ["Lakshadweep"],
    "Puducherry": ["Karaikal", "Mahe", "Puducherry", "Yanam"],
}


export { IndianDistrict, Blocks, IndianStates }